---
output: svg
---
@startuml
<style>
stateDiagram {
  element {BackGroundColor orange}
  name {
    BackGroundColor aliceblue
    Fontcolor blue
    FontSize 12
  }
  description {
    Fontcolor red
    FontStyle plain
    BackGroundColor pink
  }
  .history {
    BackGroundColor palegreen
  }
}
</style>

hide empty description 

state "Name (name style)" as s1 {
  s1: State description (description style)
  state "s2" as s2
}

state h <<history>>
[H] --> s2
h --> s2
@enduml
