@startuml
sprite $alexaskill [54x57/16] {
00000000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00000000
00000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00000
000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC000
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00
0CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0
0CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCBAAAAAAAAAABCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCBAAAAAAAAAAAAAAAABCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCAAAAAAAAAAAAAAAAAAAABCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCBAAAAAAAAAAAAAAAAAAAA99ACCCCCCCCCCCCCCC
CCCCCCCCCCCCCCBAAAAAAAAAAAAAAAAAAA998878CCCCCCCCCCCCCC
CCCCCCCCCCCCCBAAAAAAAAAAABBBBAAAA99887767CCCCCCCCCCCCC
CCCCCCCCCCCCBAAAAAAAAABCCCCCCCCB9988776658CCCCCCCCCCCC
CCCCCCCCCCCBAAAAAAAABCCCCCCCCCCCCA877665559CCCCCCCCCCC
CCCCCCCCCCCAAAAAAAACCCCCCCCCCCCCCCB76655444BCCCCCCCCCC
CCCCCCCCCCBAAAAAAACCCCCCCCCCCCCCCCCB65544407CCCCCCCCCC
CCCCCCCCCCAAAAAAACCCCCCCCCCCCCCCCCCCB5444000BCCCCCCCCC
CCCCCCCCCBAAAAAABCCCCCCCCCCCCCCCCCCCC94000006CCCCCCCCC
CCCCCCCCCAAAAAABCCCCCCCCCCCCCCCCCCCCCC6000000CCCCCCCCC
CCCCCCCCCAAAAAACCCCCCCCCCCCCCCCCCCCCCC9000000ACCCCCCCC
CCCCCCCCBAAAAAACCCCCCCCCCCCCCCCCCCCCCCC0000007CCCCCCCC
CCCCCCCCBAAAAABCCCCCCCCCCCCCCCCCCCCCCCC6000006CCCCCCCC
CCCCCCCCBAAAAABCCCCCCCCCCCCCCCCCCCCCCCC8000005CCCCCCCC
CCCCCCCCBAAAAACCCCCCCCCCCCCCCCCCCCCCCCCA000005CCCCCCCC
CCCCCCCCAAAAAACCCCCCCCCCCCCCCCCCCCCCCCCA000000CCCCCCCC
CCCCCCCCBAAAAACCCCCCCCCCCCCCCCCCCCCCCCCA000005CCCCCCCC
CCCCCCCCBAAAAABCCCCCCCCCCCCCCCCCCCCCCCC7000005CCCCCCCC
CCCCCCCCBAAAAABCCCCCCCCCCCCCCCCCCCCCCCC6000006CCCCCCCC
CCCCCCCCBAAAAAACCCCCCCCCCCCCCCCCCCCCCCC0000007CCCCCCCC
CCCCCCCCCAAAAAABCCCCCCCCCCCCCCCCCCCCCC9000000ACCCCCCCC
CCCCCCCCCAAAAAAACCCCCCCCCCCCCCCCCCCCCC4000004CCCCCCCCC
CCCCCCCCCBAAAAAABCCCCCCCCCCCCCCCCCCCC80000007CCCCCCCCC
CCCCCCCCCCAAAAAAACCCCCCCCCCCCCCCCCCCA0000000BCCCCCCCCC
CCCCCCCCCCBAAAAAAACCCCCCCCCCCCCCCCCA00000006CCCCCCCCCC
CCCCCCCCCCCAAAAAAAACCCCCCCCCCCCCCCA40000000CCCCCCCCCCC
CCCCCCCCCCCBAAAAAAAABCCCCCCCCCCCB8540000009CCCCCCCCCCC
CCCCCCCCCCCCBAAAAAAAAABCCCCCCCB97655400006CCCCCCCCCCCC
CCCCCCCCCCCCCBAAAAAAAAAAAABBAA98766544407CCCCCCCCCCCCC
CCCCCCCCCCCCCCBAAAAAAAAAAAAAAA9877655547CCCCCCCCCCCCCC
CCCCCCCCCCCCCCCBAAAAAAAAAAAAAA988766559CCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCBAAAAAAAAAAAAA987767BCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCBBAAAAAAAAAAA9988ACCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCBBAAAAAAAAAABCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
DCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCD
FCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCF
FECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCEF
FFDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDFF
0FEDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEF0
0FFEDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEFF0
00FFFEDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEFFF00
000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000
0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000
000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000
}



!define ALEXASKILL(alias) AWS_ENTITY(component,#2F74B8,alexaskill,alias,alexaskill)

!define ALEXASKILL(alias,label) AWS_ENTITY(component,#2F74B8,alexaskill,label,alias,alexaskill)

!definelong ALEXASKILL(alias,label,e_type="component",e_color="#2F74B8",e_stereo="alexaskill",e_sprite="alexaskill")
AWS_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong

@enduml