---
output: svg
---
@startuml



sprite $demo [128x128/color] {
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&_>W&_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~~%&_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~&~!!!!>W!!!!:~:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~&~!!>m>n!!&~NI&~!!:W>n!!&~&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:W_n!!&~>m&~>me+>m&~>m&~!!~%>m!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:W:V&~VpRYa*iKZpRIVp:~:V:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~RZRIiKiKiKiKiKiKiKRIRZ&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!RYiKiKiKeKeKeKiKiKiKRY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_mNI_m>W:V:V:W>W_mNI_m!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:V&~!!!!!!!!!!JJJJ&~:G&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~&~&~:W:W:W~%NI~%:G!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~&~&~:W:W_m>m:WNHZpiKRY:V>m:W:V&~&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~>mNINIRYa+VZJ%e+iKiKa*RYa+~%:W&_!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!>We+iKe+NI~%>WeKiKiKiKiKiKZpVp_m:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!>WVpZpeKJ$JIaM~%iKiKiKiKiKiKe+_m:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~_m_nRIVY>mJ&VqRYa*iKiKiKiKiKiKiKeKVp_n&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~RZe+RYRYRYJ%>WRYZpe+iKiKiKiKiKiKiKiKiKeKJ%&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~&~&~:~:V:W>W>W:~!!!!!!!!:VeKiKiKiKiKe+NHRYiKiKiKiKiKiKiKiKiKiKiKiKJ%:W!!!!!!!!!!!!!!:~:W>W:W:V:~&~&~&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:~>mJ%RIVpa*e+i+iKeKRZ~%&~!!!!!!:~ZqRYJ%~$~%RIe+e+a*iKiKiKiKiKiKiKiKiKiKiKZp&~!!!!!!!!!!!!:~J%VZeKiKeKe+a*VYRIJ%>m:~&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:V~%RYa*iKiKiKiKiKiKiKe+_m&~!!!!!!!!!!&~:W:W&~&~&~:W>miKe*eKiKiKiKiKiKiKiKiKiKiKe+:W!!!!!!!!!!!!!!!!&~_me+iKiKiKiKiKiKiKa*RY_n:V&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:~>mRIe+iKiKiKiKiKiKiKiKiKiK_m&~!!!!!!!!!!!!!!&~!!!!!!!!:WRYe+VYiKiKiKiKe+iKiKiKiKiKiKe*:W!!!!!!!!!!!!!!!!!!&~ImiKiKiKiKiKiKiKiKiKiKa+NI>m:V&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:W_mVZiKiKiKiKiKiKiKiKiKiKiKiKVp:W!!!!!!!!!!!!!!!!!!!!!!!!:VJ%eKN%e+iKiKiKiKVYiKiKiKiKiKiKiK_n!!!!!!!!!!!!!!!!!!!!:WZpiKiKiKiKiKiKiKiKiKiKiKeKVY_m:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&V>mVYiKiKiKiKiKiKiKiKiKiKiKiKiKiKRI:W!!!!!!!!!!!!!!!!!!!!&~>WNIa+J%J%iKiKiKiKiKRIiKiKiKiKiKiKiK>m!!!!!!!!!!!!!!!!!!!!:WRIiKiKiKiKiKiKiKiKiKiKiKiKiKiKRY>W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:WNIe+iKiKiKiKiKiKiKiKiKiKiKiKiKiKiKJH&~!!!!!!!!!!!!!!!!!!!!&~:W>W:W:WVYiKe*iKiKiKJ$eLZoiKiKiKe*eK>W!!!!!!!!!!!!!!!!!!!!:WNIiKiKiKiKiKiKiKiKiKiKiKiKiKiKiKe+N%:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~>WVpiKiKiKiKiKiKiKiKZpiKiKiKiKiKiKiKiKNH:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!:Va+iKVYiKiKiK~%NIe+iKZpiKVYa*:~!!!!!!!!!!!!!!!!!!!!:WNIiKiKiKiKiKiKiKiKZpiKiKiKiKiKiKiKiKVp>W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:G_me+iKiKiKiKiKiKiKiKiKRYiKiKiKiKiKiKiKiKRI&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!J%VoiKRIiKiKeK>WRYiKeKVYa*RIVp:~!!!!!!!!!!!!!!!!!!!!:WRYiKiKiKiKiKiKiKeKVYiKiKiKiKiKiKiKiKiKa+_m:~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:VJ%e+iKiKiKiKiKiKiKiKiKZoVpeKiKiKiKiKiKiKiKVp:W!!!!!!!!!!!!!!!!!!!!!!!!!!:VRZRYZpNIZpiKZpVYiKe*a*RYVYNIVp&~!!!!!!!!!!!!!!!!!!!!:WVpiKiKiKiKiKiKiKeKVpZpiKiKiKiKiKiKiKiKiKe+~$:V!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:WJ%eKiKiKiKiKiKiKiKiKiKiKZpe+iKiKiKiKiKiKiKiKa+:W!!!!!!!!!!!!!!!!!!!!!!!!:VRYJ%a+_nNIVYiKiKiKiKZpVpRYi+InRZ>W!!!!!!!!!!!!!!!!!!!!:We+iKiKiKiKiKiKiKiKe+a*iKiKiKiKiKiKiKiKiKiKe+_m&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~_meKiKiKiKiKiKiKiKiKiKiKe*Vpe+e+e*iKiKiKiKiKiKiK>W!!!!!!!!!!!!!!!!!!&~:VJ%VpJ%_nJ%:WNIiKiKiKiKiKe+J%NIiJe+RYRY&~!!!!!!!!!!!!!!!!!!>miKiKiKiKiKiKiKa*e+e+Vpe*iKiKiKiKiKiKiKiKiKiKe+_m&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~>me+iKiKiKiKiKiKiKiKiKiKiKZpiKiKe+ZpiKiKiKiKiKiKiK~%!!!!!!!!!!!!!!!!!!_neLiKZpVYe+Voa*iKiKiKiKe*iKiKZpJ%e+RIe+iK_n!!!!!!!!!!!!!!!!!!~%iKiKiKiKiKiKiKVpe+iKe+ZpiKiKiKiKiKiKiKiKiKiKiKe+>W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:WVpiKiKiKiKiKiKiKiKiKiKiKe*VYiKZoNHZpiKiKiKiKiKiKiKNI!!!!!!!!!!!!!!!!!!&~_nVpe+a*iKiKe+iKiKiKZpZpiKeKe+a*e+~%~%>W>W&~!!!!!!!!!!!!!!!!NIiKiKiKiKiKiKiKVpNIZpe+VYe*iKiKiKiKiKiKiKiKiKiKiKVp:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~NHiKiKiKiKiKiKiKiKiKiKiKe+ZpiKiKZpiKe+iKiKiKiKiKiKiKRY&_!!!!!!!!!!!!!!!!!!:WJ%~%VZiKe+RYe+ZpeKJ%eKVYiKVYZpiKNHeKRI:W!!!!!!!!!!!!!!!!&~RYiKiKiKiKiKiKiKe*iKZpiKiKZpe+iKiKiKiKiKiKiKiKiKiKiKJ%&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!>We+iKiKiKiKiKiKiKiKiKiKiKZpZpiKe+VZiKiKiKiKiKiKiKiKiKVp&~!!!!!!!!!!!!!!!!:WNIa+N%iKa*NIZpZpVYRYJ%RYRZiKRYNIe+ZpVYiKVp:W!!!!!!!!!!!!!!&~VpiKiKiKiKiKiKiKiKiKVZe*iKZpZpiKiKiKiKiKiKiKiKiKiKiKe+>W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:~RYiKiKiKiKiKiKiKiKiKiKe*VYe*iKe*e+RHZp_n_n_m_n_n_m_m_m>W:W:W:W:W:W:W:W:W:W:W_n>W>m_m:W>m_m>mNI_m>n>W>W_m>W_n>W_m>W_m_m>m:W:W:W:W:W:W:W:W>m>m_m_m_m_m_n_n_na+RIa*i+iKa*VYe*iKiKiKiKiKiKiKiKiKiKRY&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!>miKiKiKiKiKiKiKiKiKiKZpVoeKiKiKe+ZpeK_mJJNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNbNaNaNaNaNaNaNaNaNa_n>n~&NKNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNa~&_meKZpeKiKiKeKVpZpiKiKiKiKiKiKiKiKiKeK>W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~RYiKiKiKiKiKe+a*eKZpVYeKa*iKiKe*VYVoRY:WW:>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n:W:W>X>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n>n~&Rr:WRYVYVpe+iKiKZpe+VYZpe+a*e+iKiKiKiKiKNI&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!:We+iKiKiKiKiKZpVoVYa+ZpiKiKiKeKZpiKe+>W:WW::W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W>XW::W>We+iKZpeKiKiKiKZpZpVYVYZpiKiKiKiKiKe+:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!&~J%iKiKiKiKiKiKe+e+e+iKiKiKiKe*ZpVYiKRI:W:WW::W:W:W:W:W:W:W:W:W:W:W:W_nNZRaNJ_n:W:W:W:W:W:W:W:W>W~%NZNZJ%>V:W:W:W:W:W:W:W:W>W~%JIJ%>W:W:W:W:W:W:W:W:W:W:W:W:WW::W:WRYiKVYZpe*iKiKiKiKe+e+e+iKiKiKiKiKiK~%!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!&~VZiKiKiKiKe+iKe+iKiKiKi+e+a*VoiKe+eK>W:W:WW::W:W:W:W:W:W:W:W:W:W~%edvhzyzyzyvhed_n:W:W:W:W:WNZn=vizyzyvin=RZ>W:W:W:W:W>WVqr>zizyzirQa-_m:W:W:W:W:W:W:W:W:W:WW::W:W>meKe+iKVoa*e+i+iKiKiKe+iKe*iKiKiKiKRY&~!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!:Ve+iKiKiKiKZpe+ZpiKZpe+ZpVYeKVYiKiKVY:W:W:WW::W:W:W:W:W:W:W:W:WJ&rQzzzzzzzzzzzzzzrQJ&:W:W:WW-vizzzzzzzzzzzzviaM>W:W:W>miezyzzzzzzzzzzzyn=_n:W:W:W:W:W:W:W:W:WW::W:W:WVoiKiKVpeKVoZpe+ZpiKZpe+ZpiKiKiKiKe*:V!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!_niKiKiKiKiKe+NHe*RYe+RHiKVYiKiKiKe+JH:W:W:WW::W:W:W:W:W:W:W:W>mr=zzzzrQa-RZa-rQzzzzn=>m:WRZvizzzymvW-W-muzizzziVq:W:WeNzyzzvhida-eMvRzzzzmu>W:W:W:W:W:W:W:W:WW::W:W:WNHe+iKiKiKVYeKNHe*RYe*NIe+iKiKiKiKiK_n!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!JHiKiKiKiKiKiKe*iKVYiKZpiKiKiKiKe+e*NI:W:W:WW::W:W:W:W:W:W:W:WVrzyzzmu_m:W:W:W_nmuzzzyW+>Wr=zzziW+:W:W:W:VRqvhieJ&:WJIvizzrQJ%:W:W:V_nn=rQVq>W:W:W:W:W:W:W:W:WW::W:W:WRIe*e+iKiKiKiKZpiKVYiKe*iKiKiKiKiKiKJ%!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!&~RYiKiKe*iKi+iKiKiKiKiKiKiKiKiKZpRYeKRY:W:W:WW::W:W:W:W:W:W:W:Wn=zzvhJ%:W:W:W:W:WJ%vizzn=NIzyzzid:W:W:W:W:W:W~%:W:W:WeMzzzyRZ:W:W:W:W:W_n>m:W:W:W:W:W:W:W:W:W:WW::W:W:WVYeKVYZpiKiKiKiKiKiKiKiKiKe+iKe+iKiKRY&~!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!&~VpiKiKZpeKZpiKe*iKiKiKiKiKa*a+e+RYiKZp:W:W:WW::W:W:W:W:W:W:W>mvRzzmv:W:W:W:W:W:W:Wn=zzvRa-zzzyRZ:W:W:W>W:W:W>W>W:W>WmuzzvR>m:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:WW::W:W:Wa*iKRYe+a*e*iKiKiKiKiKa*iKZpeKe*iKiKVp&~!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!:~e+iKiKVpRIVpVZa*iKZoiKZpe+a*NHiKeKiKeK>W:W:WW::W:W:W:W:W:W:W>mvhzzmu:W:W:W:W:W:W:Wn=zzvheLzzzyNZ:W:W>mn=r=r>r=r=n=Vqn=zzrQ>W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:WW::W:W>WiKiKeKiKRHa*e*ZpeKZpiKZpVpVpNHZpiKiKa*&~!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!:~eKiKiKiKiKZpRYZpVZZpVZe+RIiKZpiKiKiKiKJ%:W:WW::W:W:W:W:W:W:W>WrQzzrQ_m:W:W:W:W:W_mvRzzrQVpzyzza::W:W>mvQvivizyzzzzNZidzzviJ&:W:W:W:W:W>W>W:W:W:W:W:W:W:W:W:W:WW::W:WNIiKiKiKiKZpiKNHe+VYZpVpZpNIZpiKiKiKiKe+:~!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!:ViKiKiKiKiKe+iKe*RYe+RIiKZpiKiKiKiKiKiKZp:W:WW::W:W:W:W:W:W:W:WeMzzzyaM:W:W:W:W>WeMzyzzeM_mvhzzvRJ%:W>WJ%J%RYvQzzvh~%Razyzziu>m:W:W:W:WeMmuNJ:W:W:W:W:W:W:W:W:WW::W:Va+iKiKiKiKiKiKZpiKRIeKRIe*e+e+iKiKiKiKeK:V!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!>WiKiKiKiKiKiKiKiKeKiKe*iKiKiKiKiKiKe*iKiKJ%:WW::W:W:W:W:W:W:W:W~%vhzzziedJI_nJIedzyzzvhJ%:WeMzyzzrQRq~%_nRZrQzzzzed:W>Wn=zzzyn=RZJ%NJidzyzzrQ_n:W:W:W:W:W:W:W>WW::WJ%iKiKeKiKiKiKiKiKiKe*iKe+iKiKiKiKiKiKiKiK>W!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!>WiKiKiKiKiKiKiKiKiKiKiKiKiKiKiKiKiKZpe+iJa*:WW::W:W:W:W:W:W:W:W:WRqvizzzzzivhzizzzzviRq:W:W>mmvzyzzzyvivizyzzzzn=_m:W:WJ&rQzzzzzyzizyzzzzvhNZ:V:W:W:W:W:W:W:W>nVr>We+iKZpZpiKiKiKiKiKiKiKiKiKiKiKiKiKiKiKiKiK>W!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!>WiKiKiKiKiKiKiKiKiKiKiKiKiKiKiKiKiKe+J%iKiKRYW::W:W:W:W:W:W:W:W:W:WNZrQzyzzzzzzzyrQRZ:W:W:W:W_nedvizzzzzzzzziiu~%:W:W:W:WJ%iuvizzzzzzzyn=NI:W:W:W:W:W:W:W:W:W>nRrVZiKiK~$e+iKiKiKiKiKiKiKiKiKiKiKiKiKiKiKiKiK>W!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!>WiKiKiKiKiKiKiKiKiKiKiKiKiKiKRIiKiKiK>WNIiKiKRY:W:W:W:W:W:W:W:W:W:W:W>mRaeMideMRZ>m:W:W:W:W:W:W:WJIaLitiuaMNI>W:W:W:W:W:W:W:WJIVqaMa-NI>W:W:W:W:W:W:W:W:W:W:W>nVpiKiKJ%>miKiKiKRIiKiKiKiKiKiKiKiKiKiKiKiKiKiK>W!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!:WiKiKiKiKiKiKiKiKiKiKiKiKiKiKNHiKiKiK~%:WJ%e+iKRY:W:W:W:W:W:W:W_nJ%~%_n:W:W:W:W>W~&~%:W:WJ%~%_n:W:W:W:W:V>mJ&JI~%>W:W:W:W>WJ&J%J%J%J%J%J%J%_n:W:W:W:W:W:W:W:WRYiKe*J%:WJ%iKiKiKNHiKiKiKiKiKiKiKiKiKiKiKiKiKiK:V!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!:VeKiKiKiKiKiKiKiKiKe+VYiKiKiKRIa*iKiKRI:W:W>WNIRY_n:W:W:W:W:W:Wa-zivirQ_n:W:W:WNJvhvR>n>mvQviid:W:W:W>maMrRzizivhn=NZ:W:W~%vhziziziziziziziaM:W:W:W:W:W:W:W~%RYJ%>W:W:WRYiKiKZpRYiKiKiKVYeKiKiKiKiKiKiKiKiKe+:~!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!:~e+iKiKiKiKiKiKiKiKiKNIiKiKiKa*NIiKiKZp:W:W:WRr>n:W:W:W:W:W:W:WaMzzzzzyid>V:W:VNIzyvh_n>mvhzzid:W:W_nn=zzzzzzzzzzzzzia-:W~%vizzviviviviviviaM:W:W:W:W:W:W:W:WRr>n:W:W:Wa*iKiKNHa+iKiKiKNHiKiKiKiKiKiKiKiKiKe*&~!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!&~ZpiKiKiKiKVoZpiKiKiKNHe+iKiKiK_niKiKiK>m:W:WNa~&:W:W:W:W:W:W:WaMzzzyzzzyVq:W:WNIzzvh>m>mvhzzid:W:Wiuzzzyn=VqRZaLvhzzvhNZ~%vizza-~%_n_n_n_n>n:W:W:W:W:W:W:W:WRr:W:W:W_miKiKe+~$iKiKiKe+NIiKiKiKZpVpiKiKiKiKZp&~!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!&~VZiKiKiKiKe+RYiKiKiKVpVYiKiKiKRIRYiKiKNI:W:WJJJJ:W:W:W:W:W:W:WaMzzmvvhzzvhJ%:WNIzzvh_n_mvhzzid:WNJzizzid>W:W:W:WJIn=Vq>m~%vizyW+:W:W:W:W:W:W:W:W:W:W:W:W:W:WW::W:W:WNIiKiKRIRYiKiKiKRYZpiKiKiKRYe+iKiKiKiKRZ&~!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!NIiKiKiKiKiKNHiKiKiKe+J%iKiKiKe*>me+iKa+:W:W_oRr:W:W:W:W:W:W:WaMzzeMa-zyzzn=>mNIzzvh_n_mvhzzid:WeMzzvh~%:W:W:W:W:W>W:W:W~%vizzeMNZNZNZNZNI:W:W:W:W:W:W:W:W:WW::W:W:We+iKe+>me+iKiKiKJ%iKiKiKiKNHiKiKiKiKiKNI!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!J%iKiKiKiKiKNHe+iKiKiKJ%e+iKiKiKJ%NIiKiKJ%:W>WRr:W:W:W:W:W:W:WaLzzeM>WiuzzzyaMNIzzvh_n_mvhzzid:Wmuzzn=>W:W:W:W:W:W:W:W:WJ%vizzzyzzzzzzzzr>>W:W:W:W:W:W:W:W:Wa::W:WJ%iKiKJ%N%iKiKiKe+J%iKiKiKe+NIiKiKiKiKiK~%!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!>WiKiKiKiKiKVZVpiKiKiKVpRYiKiKiKZp:WZpiKZp:W:WW::W:W:W:W:W:W:WaLzzeM:W~%vRzzvieLzyvh_n_mvhzzid:WiuzzrQ>W:W:W:W:W:W:W:W:WJ%vizzvivivhvhvhn=:W:W:W:W:W:W:W:W:WW::W:WZpiKVp>We*iKiKiKRIVpiKiKiKVYVpiKiKiKiKeK:V!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!&~a*iKiKiKiKeKJ%iKiKiKeK_miKiKiKiKN%>We+iK_n:WW::W:W:W:W:W:W:WaLzzeM:W:WRZzizzvhzzvh_n_mvhzzid:Wa-zzziNZ:W:W:W:W>WRq_m:WJ%vizza-_n_n_n_n_n:W:W:W:W:W:W:W:W>nRr:WJ%iKe+>WNHiKiKiKeK_miKiKiKiKJ%iKiKiKiKiKZp&~!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!&~RYiKiKiKiKiKJ%e+iKiKiKNHVpiKiKiKe+>mJ%iKZp:WW::W:W:W:W:W:W:WaMzzeM:W:W:WeMzzzzzzvh_n>mvhzzid:W~%vhzzrQNJ>W:W>maMzirQRZ~%vizzW+:W:W:W:W:W:W:W:W:W:W:W:W:WJ&JJ:WZpiK_n>neJiKiKiKVYNIiKiKiKe+NHiKiKiKiKiKRI&~!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!J%iKiKiKiKiKVpRYiKiKiKa*_niKiKiKiKVp:WNIiKN%S:>n:W:W:W:W:W:WaMzzeM:W:W:W>mn=zzzzvh_n>mvhzzid:W:WW-zyzzvin=murQzyzzrQ~%~%vizziua-a-a-a-a-W-_n:W:W:W:W:W:WRr>nNHiKJ&:WZpiKiKiKeK_ma+iKiKiKRIZpiKiKiKiKiKJ%!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!:We+iKiKiKiKiK_miKiKiKiKJ%VpiKiKiKiKNI:WRIe+NZJJ:W:W:W:W:W:WaMzzeM:W:W:W:WJIvhzzvh_n>mvhzzid:W:W:WW-vhzyzzzzzzzyn=J&:W~%zizzzzzzzzzzzzzzvhJ%:W:W:W:W:W:WW:>me+NI:WNIiKiKiKiKVZJ%iKiKiKeK_miKiKiKiKiKe+:V!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~VZiKiKiKiKiKRIVpiKiKiKVp_meKiKiKiKeK>m:WRYVp~&:W:W:W:W:W:WVqn=a-:W:W:W:W:WVqn=mu>m>mmun=e::W:W:W:WJ%aMn<r=iuRq>m:W:W~%mun=n=n=mvn=n=n=mu~%:W:W:W:W:W:WRrVpRY:W_miKiKiKiKeK_mZpiKiKiKRYRYiKiKiKiKiKVY&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~J%iKiKiKiKiKe+_niKiKiKiKJ%NIiKiKiKiKZp:W:WRYJ%:W:W:W:W:W:W:W>W:W:W:W:W:W:W:W>W:W:W:W:W>W:W:W:W:W:W:W:W:W>W:W:W:W:W:W:W>W:W>W:W:W:W:W:W:W:W:W:W:W:W:W:WNINI:W:WZpiKiKiKiKNIJ%iKiKiKiK_me+iKiKiKiKiK~%&_!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:Ve+iKiKiKiKiKN%VpiKiKiKZp>WZpiKiKiKiKNH:W:W>n:W:W:V:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:W:V:V:W:V:W:W:V:W:W:W:W:W:W:W:W:W:W:V:W:W:W>m:W:WNIiKiKiKiKZp:Wa*iKiKiKVpNHiKiKiKiKiKa+:V!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~RYiKiKiKiKiKa*_niKiKiKiKJ%>ne*iKiKiKe+>W:WVrUXIWgXcWgWgWQW:W:W:W:W:W:W:WMWgWgXgWgWgWgWcX>W:W:W:W:W:W:W>GcXgWgWgWgWgWgWcX>V:W:W:W:W:W:W>WcXgWgWcXMVVJ~&:W>me+iKiKiKe+>WNHiKiKiKeK_ne*iKiKiKiKiKNI&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!>miKiKiKiKiKiKJ%VZiKiKiKe+>n_me+iKiKiKRY:WNal*kWoWoWoWoWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWoWoWkWkWq:>X:WVZiKiKiKe+_m_ne+iKiKiKRZJ%iKiKiKiKiKiK>W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:VVYiKiKiKiKiKa+_miKiKiKiKRYNK_me+iKiKeK>m>nproWoWoWoWoWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWoWoWoWoWi::W>miKiKiKe+_mNaVpiKiKiKe+>ma*iKiKiKiKiKRY:G!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~_miKiKiKiKiKiKJ%NIiKiKiKiKRqRr_me+iKiKNI:Wm;oWoWoWoWoWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkX>W:W:W:W:W:W:W>WkWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWoWoWoWknW::WNYiKiKe+_nRrRqiKiKiKiKNINIiKiKiKiKiKiK_m&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:WVoiKiKiKiKiKe+>Wa*iKiKiKa*eNNaJ%iKiKa+:Wa:oXoWoWoWoWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWoXoWoWpJNa:Wa*iKeK_nNaaMa+iKiKiKa*>We+iKiKiKiKiKRY:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~_miKiKiKiKiKiKNH~%iKiKiKiKVZn>JINIiKiK>mRap*oWoWoWoWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWoWoWoWps>n_miKiKNHJJn>VZiKiKiKiK_mRIiKiKiKiKiKeK_m&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:WRYiKiKiKiKiKe+>mRYiKiKiKiKRZrR_nVZiKNH>nproWoWoWoWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWoWoWkWi;:WNIiKRZ~&rRRZiKiKiKiKRI_miKiKiKiKiKiKRY:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~>We+iKiKiKiKiKVZ>WZpiKiKiKe+a:ee>We*Vp:Wi:oWoWoWoWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWoWoWonW::WZpa*>Wn>W-e+iKiKiKZp:WVpiKiKiKiKiKe+>W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:VNHiKiKiKiKiKiKJ%>me+iKiKiKVped>X~$e+:WW:knoWoWoWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWoXoWpa~&>We+_m~&eeZpiKiKiKe+>mJ%iKiKiKiKiKiKJ%:G!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:WZpiKiKiKiKiKe+>nJ%iKiKiKiKRZ~&:WRZ>mJ&paoWoWoWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWoWkWm;:W_nRY:WNaRZiKiKiKiKJ%_ne+iKiKiKiKiKVp:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~_meKiKiKiKiKiKVZ>nRIiKiKiKi+_m:W>W_n:Wi:oWoWoWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWoWkXa::W~%>W:WJ%iKiKiKiKNI>nVZiKiKiKiKiKe+>m&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:WNIiKiKiKiKiKiKNI>nVpiKiKiKa*:W:W:W:Wa:knoWoWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWoWpaJJ:W:W:W>We+iKiKiKVp_nNIiKiKiKiKiKiKJH:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:WVpiKiKiKiKiKe+Na>na+iKiKiKNI:W:W:W~&pboWoWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWoWmN:W:W:W:WRIiKiKiKZp>nNae+iKiKiKiKiKVZ:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~>We+iKiKiKiKiKVpRr_me+iKiKeK>m:W:W:WiNoXoWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWkoVs:W:W:W>miKiKiKe+>mRqVpiKiKiKiKiKa+>W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:W_neKiKiKiKiKiKRYRa_neKiKiKRY:W:W:WRroooWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkWpr~&:W:W:WVYiKiKe+_mNqRZiKiKiKiKiKe+_m:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:WJ%iKiKiKiKiKeK_m:WN%iKiKeK>W:W:W>nq:oWUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXe::W:W:W>meKiKiKJ%:W_meKiKiKiKiKiKJ%:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:WRYiKiKiKiKiKZp:~:WRYiKiKNH:W:W:Wa:knUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WlKNZ:W:W:WNIiKiKNI:V:~ZpiKiKiKiKiKRI:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:WZpiKiKiKiKiKJ%&~:WVpiKVp:W:W:W~&prUW:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WiN:W:W:W:WVpiKVZ:W&~NHiKiKiKiKiKVp:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:G>We+iKiKiKiKe*:~&~>Wa*e+:W:W:W:WeMUX:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:W~&Rb:W:W:W>We+a*>W&~:Ve+iKiKiKiKe*>W:~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:W_neKiKiKiKiKJ%!!&~_meK>m:W:W:WJJVa:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W:WW:>W:W:W:W_neK_m&~!!NHiKiKiKiKiK_m:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:WNIiKiKiKiKZp&~!!&~NI~%:W:W:W:WaN:W:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:W~&Rr:W:W:W>XJ&JH&~!!&~ZpiKiKiKiKNH:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:WVpiKiKiKiK>m!!!!:W>n:W:W:W:WJ*Na:W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:W:Wa;:W:W:W:W:W>n:V!!!!_miKiKiKiKVZ:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:W>We+iKiKiKNI!!!!!!:W&~:W:W:W:Wa:>W:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:WJJNa:W:W:W:W&~:W!!!!!!NIiKiKiKe*>W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:W~%iKiKiKVp&~!!!!!!!!:W:W:W:W_oVr:W:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:W:WaN:W:W:W:W&~!!!!!!!!&~ZpiKiKeK_n:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:WRYiKiKe+:~!!!!!!!!&~:W:W:W:WVr~&:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W:WRrJ&:W:W:W:W!!!!!!!!!!:VeKiKiKRY:V&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~>Va+iKiK>W!!!!!!!!!!:~:W:W:W:WaN:W:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:W_nW::W:W:W:W&~!!!!!!!!!!>miKiKa+:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:WJ%iKiKJ%!!!!!!!!!!&~:W:W:W:WJJRr:W:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:W:WaN>W:W:W:W>W&~!!!!!!!!!!J%iKiK_n:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!#:WVpiKJ%!!!!!!!!!!!!>n:W:W:W:WVr~&:W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W:WRrJJ:W:W:W>WRY&~!!!!!!!!!!N%iKVY:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~>meKNH&~!!!!!!!!!!NIJ%:W:W:W:WaN>W:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW>W~*Rr:W:W:W:W~%Vp:V!!!!!!!!&~NHe+>m&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:WRYNH&~!!!!!!!!&~RZJ%_m:W:W:W>na;:WQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWkW_naN:W:W:W:WNHa*>m:~!!!!!!!!&~NHRI:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~>mJ%&~!!!!!!!!&~:WVpa*>W:W:W:WJJRrQWoWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWoWknaN>n:W:W:W_meKiKZpJI:W!!!!!!&~JI>W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:W>W&~!!!!!!&~J%ZpiKiKVo:W:W:W:WNahboWoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoWkXm;>n:W:W:W>Wa*iKiKRY:W!!!!!!!!&~>W:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:W!!!!!!!!!!&~J%iKiKiKNI:W:W:W:WRqpaoWoWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWoWoXm:~&:W:W:W:WVpiKiKiKeK_m!!!!!!!!&~:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:W!!!!!!!!!!>me+iKiKiKiKJ%:W:W:W:WRrpakWoWoWoWkW>W:W:W:W:W:W:W>WkXoWoWoWkXm:~&:W:W:W:VRYiKiKiKiKiKe+:V!!!!!!!!:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~!!!!!!!!&~VpiKiKiKiKiKeKIm:W:W:W:WRapqoWoWoXkW>W:W:W:W:W:W:W>WkWoWoWoXm:~&:W:W:W:WNIiKeKe*iKiKiKiJNI!!!!!!!!&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!_miKiKiKiKe*iKiKe+>n:W:W:W:WNam:oXoWkW>W:W:W:W:W:W:W>WkXoWoniN_n:W:W:W:W>neKiKa*ZpiKiKiKRYJ&&!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:W:W&~!!!!!!!!&~&~:W:W:W:W:W&~!!!!!!!!!!!!!!>nNHe+iKiKVoa*e+iKNI~&:W:W:W:WJ&mNonkX>W:W:W:W:W:W:W>WkXp*eN>n:W:W:W:WRaRaeKNHZpRYiKiKiKNI&~!!!!!!!!!!!!&~&~:W:W:W:W:W&~!!!!!!!!!!&~:W:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!>nee~&:W:W:W:WJJa;een>rRrRivRr:W&~!!!!!!!!!!&~_miKiKiKVpRYNHe+NIrRJ&:W:W:W:W>neNlK>W:W:W:W:W:W:W>WlrW-:W:W:W:W:WRrrR~%NI_na*VpiKi+Voe+JI:W&~!!!!!!:W~&aNn>rRrRiveORr>n:W:W:W>nNaW::W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:WaNrRrRiviviveeRr>n~&>n_nW:eer>>n&~!!!!&~:WJ&a+Vpa*iKa*VZNHNJ_neeviJJ:W:W:W:W:WRrVr:W:W:W:W:W_naNJJ:W:W:W:W:WVszzrRivviJ&RZNZVpa*RY>W>W&~!!!!!!&~Rrr>aNRa>W>nJJ>naNeeivifn>vin>JJ&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~NaeeaNaNeen>viaN~&eeivW:~&aNW:Rr&~!!!!!!&~:~:VNIVoVYNYVr_nvRrRn>zzviRr:W:W:W:W:W~&aNNJ:W:WRrW::W:W:W:W:W:WaNzzzzzzzzzzn>a:W:NJJ%Zq:V!!!!!!!!!!:WeeRrRr~&eeivW::WvivRivaNaNaNiv>n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!>nvizzzzzzzzzzW:>nJJeeaNeeNa_n>n&~!!!!!!!!!!&~VpJ%JINJivn>zzzzzzzzzzzzaN:W:W:W:W:W:WNaaNaN~&:W:W:W:W:W>nivzzzzzzzzzzzzzzzzaNrRNIZpRI&~!!!!!!!!:W~&~&W:eeaNaN>n>nrRzzzzzzzzzzee:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:WeezzzzzzzzzzRredW:~&n>eeaNivRa&~!!!!!!!!!!J%e+RYn>aNvizzzzzzzzzzzzzzzziv>n:W:W:W:W:WNa~&:W:W:W:W:W~&rRzzzzzzzzzzviVrRaierReeRYiKiKJ%&~!!!!!!:WiuieaNn>aN~&n>JJrRzzzzzzzzzzJJ&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:WRrvizzzzzzzzzzNaRrzziv~&Rrr?rRRr&~!!!!!!&~_me+iKe+Rqn>eeRaNJn>zzzzzzzzzzzzviNa:W:W:W:WNa~&:W:W:W:WRrvizzzzzzzzzzzzRaVpe+RY>WRYiKiKiKiKRY>W&~&~:Wa;aNee~&NavhrR>nn>zzzzzzzzzzn>~&:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~&~:W>nRrn>zzzzzzzzzzzzzzJJeeaNviviaN>WRaNJ:W&~&~>WNIeKiKiKiKa+>WRYe+e+J&vizzzzzzzzzzzzzzee>n:W:WNa~&:W:W_nivzzzzzzzzzzzzzzviJIRYe*iKZpiKiKiKiKiKiKeKVpRYRYRYRYRZJ&virQaNRaivzzzzzzzzzzzzvieeJJ:W:W&~&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!&~:WNaivvizzzzzzzzzzzzzzzzzzJ*iurRW:rRRrRYVpVoVYVYZpeKiKiKiKiKiKiKVpe+iKRIRZeezzzzzzzzzzzzzzzzrRNa:WNa~&:WRrvizzzzzzzzzzzzzzzzrRJJNaJHRYRINIRYiKVoRYe+iKVYNIVpe+J%a-RZRreer=W:eezzzzzzzzzzzzzzzzzzrRee>n:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:WaNvizzzzzzzzzzzzzzzzzz~&n<muzyeeJIW-NJZpVpNINIiKiKRYNHiKRY~%JHRIJH~&aMeOzzzzzzzzzzzzzzzzzzzzivNaNan>zzzzzzzzzzzzzzzzzzzzzzW:viW:RrVreeNaRIa*NJ_ne+i+RYJIVreeivNHeerQmua:WNzzzzzzzzzzzzzzzzzzrRNa:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:W_oaNn>vizzzzzzzzzzvi_nmtr=rQviNIRrRrRaNZVYe+eKNIJ*VpVp:W>X>X>nJJivaNr?zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzviivn>eeaNRrJJ>n_me+e+NI_nVpiKVpNJaNee~&rQr=mteNRrzzzzzzzzzzzzviivRr:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~&~:W>n~&JJNaNaNaNa~%n<muvizzRreeviRrNIiKZp~%NIe+iKJ%n>mveeW:NaJ&~&>n~&JJJJNaRrRrVsW:W:W:W:W:W:W:W:W:W:RrRrNaNaJJ~&~&>n~&JJRraNeen>viaNVZiKNHNIJJNIiKNIn>aNn>zzr<mued>nNaNaNaNJJJ~&:W:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~&~&~&~&~&~JJmur=vhzzviaNrRNIiKRYW:JINIe*e+NZvizzzzzzzzzzzzvivirRn>mwiveeeeaNaNaNaNaNaNaNaNaNeOeeivivn>n>rRvizzzzzzzzzzzzvirRivJ%VpZpJIn>W:VpRYRrzizzvivQmtmv:W&~&~&~&~&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~NamtrQvhzzzzzyaNJ%e+NZzzJIZqVZNIeeeeaNaNeeeeeeivn>rRvizzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzvirRrRiveeeeeeaNaNaNeerRn>RrZpJ%viivRYiKNIedzzvir=n<r>:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~Vrr<n<zyzzzzivNIiKa*W-zzNaVpVrivzzzzzzzzzzzzvirRn>iveeaNaNeNeOeOeOeOeeeeeeeeeNeeeeeeeeeNaNaNeeeeivn>vizzzzzzzzzzzzzzzzzzNZRrzzivRYe*iKJIzzzyrQr<r=>n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&GeNmtvgvizzzzW-a*e*VpW:zzivJ&r>zzzzvivizzzzzzzzzzzzzzzzzzzzzzzzzzzzzzaNvizzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzvizzzzzzeeJJvizzrR>nNIZpadzzzzvhmtvQJJ&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~a-mur=vizyzzrRNIVp>WivzzzzW:RavizzRr>W>nRrvivieeivrRzzvivizzzzzzzzzzrReezzzzzzzzzzzzzzzzzzzzzzzzzzmwn>zzzzzzee~&zzzzn>eevizzzzzzRr_nRYnRzzzzrQr=r=~&&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~_omurPzzzzzzzzNJNINKvzzzzzzzn>ivzjJJaNrRJJRrn>:WJJJ*rR_n>WeeeeJJNKivivaNzzzzzzaNNaivzzrRJJ>nRrzzNa~&~&RrzzzzJJ:Wvizzzzzzzzzzzzzzzza:Razzzzzzvhmuee:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~J&r>zyzzzzzzeNNZvizzzzzzzzzzzzzz>nivzziv>nee~&vizzaNNan>W:W:JJa:>nW:NazzzzzzrRJJaNzzRrRrrR>niv:WrRn>>Xzzn>Na~&n>zzzzzzzzzzzzzzeNJJrRzzzzzzvhee:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~>naNvizzzzzzW-NarRzzzzzzzzzzvi:WvSzzee~&aN:W>nRriv>nRbrRW:NaaN>nW:NazzzzzzzzNaaNzzNaVsvi~&iv>Wn>vi:WvSNaivNaaNzzzzzzzzzzzziveevizzzzzzrRNa:W!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:W~&aNvizzzzn>ivzzzzzzzzzzn>:Wivmw~&W:W:RrvirRvRn>JJNaRr>nJJiva:NazzzzzzzzRaaNzzn>>n>n_ovi_nivvi:Wn>>n~&:W~&vizzzzzzzzzzzzzzzzzzn>Rr:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:~>nRbivvizzzzzzzzzzzzrRRrJJ~&W:viRr~&W:n>JJaNW:NaRrW:zzzzW:RrzzzzzzzzRra;zzzzvi~&eezzNaJJW:>XviivrRivaNzzzzzzzzzzzzzzrRaNJJ:W&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~:W>nJJaNivvizzzzzzzzzzzzzzzzn>aNW:mvn>~&J&r>RraNzzzzW:RrzzzzzzzzRrW:zzzzeeNazzzzviW:Rrn>zzzzzzzzzzzzzzvirReeRr~&:W&~&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~&~:W:W>nJJW:eeivrRvizzzzzzzzzzzzzzzzzzzzzzzzzzvivizzzzzzzzvivizzzzzzzzzzzzzzzzzzzzzzvin>ivaNRrJ&>n:W:G&~&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&~&~&~:G:W>W~&JJNaW:aNeeivn>n>rRvivivivivivivyvivivivivirRn>iveeaNW:RrNa~&>n:W:W:G&~&~&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!&#&~&~&~&~&~:~:W:W:W:W:W>n>n>n>n>n>n>n>n:W:W:W:W:W&~&~&~&~&~&~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}


sprite $demo16 [128x128/16z] {
n9L7siCw30Dt0C7c-v_s5Jc9wRztJxAAh6yec5Isxr7RjSI5xkvr_kvhx5lcrjvRvHKbL6vRRedgshQeAz9l4s5kVSaRQ3bsfDukGBYZxGhIixghqlEo-ViV
z-xBRe2k2i--o9rPJgYg_Zo2T1Sj253y-_alW1w5XLds7-lD4874Wbb_wkzCLuQ9kF6t0OYIecGuYFxrVg_QOsuiN1WyMd0zrZyh3hSLjTOfcueC9uW3koax
LYeqZvyeepjrr_3-agkxk-haPntTyTYW_5u9NHgExDEQO1ZKQ4yye5T_sPudWTLfCH3xpzZ9EPqOAFkBPyS9hxdeZDtlsAdXTvpG5p8e1yvudwgh4WWWLWAS
_XvxlpQTVKJ8wPyqbpcT88mz_SysswSYw2Jkw3L_sCg-18Xkqw-nUGpFH-d00xDJ_qs9w0G5KZhvo-RkEzbVqCF6X9_rmNJj4Y5Lmq_S8F7f0ZfnG2FuVC8x
B3BAiGW7fE773a7xV075wGVuVC9p5MQyFM49dyiniZlVaH_HszmXc1CxlZr80x4mBabarNR7xtutwDcVnDkqJxtD1fW9HmWKYO0WmkVrf1cVVUuUA9pz5ExO
k9mOe9kPGeASfZ4VXz888mQrlKrhXa-0RdcZ3h9oVJspAjTdhkSDEd7kGVM7Zq_R4qpNgsJ5MwkvfpyBg0yTdp3jlMzgvgjKLRvAMCkC0A57ltf_OFRCHEuJ
n6fM_yjvcI1P2kD0bC-YFJttl-rOHbz3hqnqHa2RhYezAoKRK_eEMlZrVmPwo03V3Z1hdHRvhtodfrY4R4n-AME6gGM-13TpDC-_3qWbVoXL9hqHnBlzpmR8
C0Eb4TTdsxRF5OjYnpPrw3qpsUV3pj4J0C_1e_pl7JXuSIUOaoxvsm0N7F14f7PFUxSIJNwSzN14ySVWELexY6H0ONuhG5IFiBBHyc9nslmZ4rJUam9D67Do
PU1AMpZjEL7fhyQnbNE5V2k0T_TJTOiz-Jo3PtOnvy7OyvQ-VouVbfuWVxGBEdyCM7KqzGhmF_CrsTHY9Mt-Il_ZQn7uPpjiPJg5oGLjcuvK04__eLIDtz8_
br-IppK7PbBY9tzIaVWr4rv4bEP_e5Vei_vCoglm7Lh-sdvY8fncyLql_8yVdxksDtzcRCllgKEERI_qZtpS_SJBVn6JlpNWe9IeJB7TBU1e_gpu7gDciiii
_ngbTBQVtzQaGxZ5rNv2nYkaK6gyRVwiLFISROPPLD2zrB06ySbkWBlksoUqkW5q6Xxhdubg1cGvVkMNk4S-ckypsSl3hYtHD5jU8YP-kv1Byr2tSqkFck-F
W2syybl2n2Z-bAJRot5Pg_2nvVJMzD5l_I5WuWR_2v-TIBdvq9koQpx6bUFQ4uQVzroizzyG9Of_vzkyO6iFBlvawdMIHhtfZCwJh7u4P-9wMEb3Y1mPwD_v
Ffn9Yn_kDzaTkCT0r5iFNeeRFw34FlnN_ilwMzAyE7CVC8rQptTp3PiDFzl_oYdHFaj-A79Fl4LLhj2SbnAnLi1NFl-GEzkyC8PyCw8jM_t9xnvaU8sQZ_Lt
J6JyWmVyylgL_lN8Qmprva_9Wu_PSuSepQr09vzZAVafIHCg35j_3Sf__YWXAhiaRwRpcZXh_h4sdURRxSUmGv3yVW4yNx-wx9UkWVwPR-qz-RmOUOsGvbyy
4yQNZsiEYZScdtJAK7mmqdx6DnnL-BVtV_F9RLw0B43oAHsduf_puUYb-Qt_ZaV-JkGhamS_tax_8jy2C8Ga4sd-Uk5GyszQypzJ1_3DFzCNS9AbQZ25b_DV
vHvhniWEVFA7JapnHvq1Lgjt_tth7m8dXdKmVp-0Q_FlAHCyC-Zwqq2UzAh-kUPt0uAsNPF__2w06vXYaTMw1gIlv__oFjOGHYveVft-AlyqO3lEFGz_at_o
Kjny3IE7hFIh1Yb___mhksJPC9JLdtpOf_SVyBth7Px-btpn1mTP7N-heE_VFqEelPUWL435nn8Vd7p8SKQS1-M3qt6SQL0SfRFUJYAAe4vVzVq3k0fGthlT
5O1wxofvQotCgD5u_7SAPW2lR2hzT_jh1PJtN7y-4D-ODOaM-lQB40EL0EVTtkrFlZuDMCOHXZXyAggrms-XI5vQPjHpcWOYwXN8hv_VtO5jGAsUeMAfA7_3
Rg4gOgKSzpFXpgLY-AzdZtS3rDO_2Fez7t_Z3wmuAYi4ltPVQH6x-IGV3TUJZ_yhVrvhBsJXxVtRyx-rcuUwsoeCW9dQulqVztuICTsravwhBZSk_6WWcqZz
VWkUuCCq72vycqyS4nX3JlDS_ME0RNhgAZ4DlSi7jr2xKwhDZzK_4G2UVt8pZhMypnTWQtnKUQh-sGAqFO3JaTQxVCP5w1ttH9TB3-BHLx2wFJ3Tq97VuwCw
cCu4cxvPXBdMkmUoEflYU_pfnelvPB5JltYd0i0xRYmICBof_p9VkfrFRvKVZWVEMFJbwptzKPQldVTDtY-17GzmsaxMMehlyFEjd7V-UzFwAUjy4PiBYDb0
H9_oyyXiYQShze_wxuK0M_oUpLRFzGTxgM_CDyw_Au9PNdYeyuplmO-dSlhSFkvEyBro2aKo0l2n_Id-kUIeLzvFvtzMWjK8Hie8rBKUwP_nGb5jahlYwtqC
ueggG4mDZ_XhASNcYtIxy3RsxcDGuv5eOL5wniTGt-9X9xUnTr-33pCkqJI0F-4hxNV2zL9V_FFc3tgziwLUI_cMVtdVm-PsKtDy60AIIrcxe7BB5yx-cr1Q
FdV-oG97Wz39oDSDVpjfZw0Rvpzz6TfJvCws6_tNFgljiMVd_wC7V5-cTZTyGpzyEzR_Hm_e5OuPt7_ZE-G7vopv1MrfJXVV8hUHhZ_pj_MTBpxxLpJRWUoh
amJ-oDzRtsXhBU3hQngDNt-gPMBxe_wMrfVBwV95VSccrmC9WwZq9pxin0ie2Vwghj1NF2a1SF0OVt_-pAgiuzbqlhwKdxb8iWo2l-FFZ3qwvwolwyhtxshp
6uA_ycT4vtLwzpFiA-Haqn0x2pZ-FzelUHMQ94TyYllpiHXp0RwSuGS-lohohw8zwyt4DutLvo9CUl7bLHiGpKGu-HkVm0FF34AyrVzrYfCNxyJIbQumUsk3
V7qp0B6WD0sg0GK_GnuJJzN4TikG97Cfn0oJqcUC3nsoeBOnOfYwuMosepzRmKZ4His2HAQ3N4YwtgcqKPMPaDqJJmtOJGpc6BqsUPpm9i3i1NHsDC3h-Iz4
GbPRBoK8GPQzYfKL-906AFfIr2UHpe5Uwm20uOyJNab1amcJxNg8aOgCVbekqgQmbSzAq1PeWhBvfZW1p6lUcEifVyqSG1ErJ-YyhiTPXt99jpG-1_vKNoln
Q2CMbVmne8FrrqrzwdwdlM2cCfHQetLwxlfawLUTrrVoFLo_9NtFLykh0qpbscoFw0yMa77KonQPMN1dYKzbvpK6E8N6wPxwdzQNAeodtuquH4i3lkxdlhe9
lL7B9JegDc8YvZCfWF0ivPY0rUcCQCBAB0p4k_bFaMbsF0DAcpTlH0xbYFLUfg0GYMGDXLL556Ovqfbx-IPOaMYoe5WCeDbbjW7mZS_h_dMdNVpHMfLGdm54
YTpTPUJztqeTVG296Q0O0GbCpVnptMPVJ-BFL8IPhOzQQ1OI81K4xNqYgvcgC1FXaLYZn0qX6Ar2FXq4f4CllKzZPdcx7tzfRxLKQ0AC8eXIBprRwsFE2I-P
aTzQFRU74ab7Oig_ZGyVn3nQJ0cAN0H9vWpK3DHlhP-B0e3HEf6MmI2pbDRRP_n5lMT31I0MfhCjDsR-A10v_gmhSqTd14c-VSQ7t8lXNYmZajXbuIDGo-zb
PerEQ8Rzctx6nzuogL0aT-HIo8rgdV7n1hVv0pNjDRIKFkC-PMzEQptvxuibluX8JZwAG1FkBjhCvnGP0y88F4eLfy9cL8hwCGfohB_FzUdHB_d0tn9IwHRw
0NT4GKz04oX4pOQtvgMpzkE4jD_qVpXwRJMsHjLhcGfkr9qRCcn-OIXCDVZLAm_EGPSJ6lk_7VvgcZwa--YAI57a5oQJSVZTt8gDujtZwaWZN_zw-E1n9XF5
GefT09cm5CpCIf0FgyA2NaSRS2K4aAyvWBf0Fq7L9_QksWWE7qkPN4f5waVnGPhmhv5i_CNSUJTIsm3I_-K_HEwgiZ32p7HV3pDJBo2nsldwvN-JjSM_bxK-
nVu7
}


sprite $demo4 [128x128/4z] {
xPg7igkmiWMdU_t_Dx-0RAQaCcLWKzStzObinEhH80jEoBysvfVyT_xyiWe5DJ-p3_GtVjxusxLdVeh_qNx1tuWL1V0N5G2Qdtq05IKCVhBez5SxWAX6uISL
iA7ye_mgz49ZdlpituVw-3wV6IRIFDWKuKWl7lX3urDs_AoNmQdhxjl1LN_I3pvW1p-F4B_vmVlwummGY01ouk8BiEDHXEv-qOz-sRavUR_v1VJ8Vwi0QGu3
b2Y0IYO_7ybP-EvNO-nPwj7TQoxhvumqW9rj4DR-WIpSs7ImDSSh33ybg0YDr_N8Hx-2W8WW7aHSBO0pVX5yWQBumU_Yv_hQr_j__4K0hpHWrKCy9j5ZFXLm
TleAW1h-_ewe9nlG2tT3o6r_IC0byj8ZLrpzQdPSZrQ_I7FHBv3PJ_q_PCFQCEaZPdy0ppy9QJ4YEFcjDxvgsPrzDFi5KRgCxtuH4LR_9fDXSJk2KGtx0RD_
2OHJgn-1rSyxVBEyLHPknJXEEVkNGF2Rlt7slnt3riiW2UtDubUQgtuMV_-kZTEfrGzosW-eWW32wYUhlpOyzWE22Ah0b-MdQY_0e_bRHVkF-j_BJr7uxWTs
Ex2il_vDRKgrgk9-YcdzBO6d_3Estwh2oAOUFuylZZweL5NQBnEN_GA7-q_jhATU6FxeHv3iE3dexI-HLH-5tFSBn0_lTlR1UhIEDO3t_Ku5QF-gorFF5xFU
UtvtVzhqNbnM9TDZn_G2OAfs3xhknp7OfFtC_fP-yByYvPA_XmTOvr-sVtn5nyzjNlm14D0p-tyFLN3rb-r_EotJ_lNnttcSzSyDQ3zKLVlfpMRpgzh-QVft
_0gsdw7ao3zOjd_jk7FlFzqm8YQa_QagJll1TEH9V_SU0xD_UDhla2UVrfyGEuolVjlV3PZzeVtscwYkVb_50zf-J_ZjcYCw-TF-KGjLB_-Wfu-neqxu0_Fu
Bg3zjZ_KmBW-00d6PJwGd6o00I1nySUYYw4ACss50pNXslJZXmP4SuDTtzF_xW-ibvZR260w4P8B3UWxaFd9EfWFv-EUVfRfNsb008nwrIzvYIzDVrq1UKNS
yWF4QzFl1dG1tlFR-fx-jGQ00dVy1bZ3SWQWbsqfnCj-4j0Iw39E8VH5LiHmtIzcwEtfNsu0aBl-503szC_XT0T8kEp7416WyvehTy0OkUXFZ3UwFzy1zxPT
zoTUx7xZLC1r_vZif3Ut2dXVAfVyUyOzVU-2cHfmoJ_qtVtx1PZaGlzx-lVrlMhS6t3D3zWh-Mu19eARtxD-apZh_rR023phPrnjHznZltLiYMVzupVG2NUP
_mhOatxsd_sRFWAug_dgxpArwx-FK_rwnazs_gfV4pZXrwNwF-7aZz_zp1VdZmXSyMjs0FDNW3HyyvC6UFe_6EgntqKlv074D7hitylh2vy0q-gGOxzcykSH
dFpXsC-arJo3ytFT8p_pgZUFegzW-UoVzSyZKm6h7wSzxtcW2vZygnxoE7EqJFvLZtaUc0gO_UnZ13JFunGkBNdh5HNmYGr7g2ew2r2nx54RlFGLWo1cmoq1
Bsv7L04O4wXiY80QQWx4bxueTRV7miG0L9MNLbeLKeIEKqrLHs5NGMs0aW4ga2e0SfhQ83BixQS6h0z7wWLbLmpGSQVeCC62wiTPKJlJ7cyDb68l2YXIreOv
HQTfeTriiD1wOVjRZ_tI742hKfSAQ05KyLO04C5wmTjFjHyPEAYYRvhVvTIE5EM0WQ3qY6Yi7GSeg8XIK3la2zHEgWfH5HGte1gjQYWKnO1AIG6rOxx2xcUV
4gYzAnr1WIPWHC4giFj_3ZTIL4afTfQ90tRwzK_OcuR5fdtdNSJ-FFFoDonCvrGBTOpCFUILXYNQgYFs0SFFA-6klpO4IcqD1ophKl0lVdZ9fB0-G1s0LHLb
6-HDVsre68acpb8Er4p_9cZkyVRtGYojQ2MWm2Pak4PvPYwbYjp4FQKtf60L5aZ6gLTPP1kXp-Zx5c3xaSIATU0NcMwE-HDqKeLzJQkHtLz9AbIgxziJzlcH
f59A2KfL-qjAIL5GBp3F8DL0bTRinyrNEsYUHQWpCAaVHm4-M47Dlnh_2m
}


title Test on <$demo> <$demo4><$demo16>

class Foo {
Test <$demo>
Test <$demo4>
Test <$demo16>
}


@enduml
