@startuml
sprite $importexport [58x58/16] {
00000000000000000CCCCCCCCCCCCCCCCCCCCCC0000000000000000000
000000000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00000000000
00000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0000000
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0000
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCD0
DCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDF0
FECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCEFF0
FFFEDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEFFFF0
EFFFFFEEDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDEFFFFFE00
CCFFFFFFFFFEEDDDDCCCCCCCCCCCCCCCCCCCCCCDDDDEEFFFFFFFFFDD00
DCCCFFFFFFFFFFFFFFFFFFEEEEEEEEEEEEEFFFFFFFFFFFFFFFFFCCCD00
ECCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0CCCCCCE00
FCCCCCCCCCCCC00FFFFFFFFFFFFFFFFFFFFFFFFFF00CCCCCCCCCCCCF00
FDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCF00
0ECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDF00
0ECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCE000
0FCCCCCCCCCCCDECCCCCCCCCCCCCCCCCCCCCCCDFECCCCCCCCCCCCCF000
0FDCCCCCCCCCCDFFDCCCCCCCCCCCCCCCCCCCCCCFFEDCCCCCCCCCCDF000
00ECCCCCCCCCCDFFFECCCCCCCCCCCCCCCCCCCCCFFFFECCCCCCCCCEF000
00FCCCCCCCCCCC0FFFEDCCCCCCCCCCCCCCCCCCC00FFFEDCCCCCCCE0000
00FDCCCCCCCCCC00FFFFECCCCCCCCCCCCCCCCCC000FFFFECCCCCCF0000
00FDCCCCCCCCCC0000FFFEDCCCCCCCCCCCCCCCC0000FFFFECCCCDF0000
000EDDDDDDDDDD0CC00FFFFEDDDDDDDDDDDDDDD000CCCFFFFDCCEF0000
000FFFFFFFFFFF0CCCC0FFFFFFFFFFFFFFFFFFF000CCCCFFFFECE00000
000FFFFFFFFFFF0CCCCC00FFFFFFFFFFFFFFFFF000CCCCCCFFFFF00000
000FFFFFFFFFFF0CCCCCCC00000000000000000000CCCCCCCFFFF00000
000000000000000CCCCCCCC0000000000000000000CCCCCCCCCF000000
00CCCCCCCCCCCCCCCCCCCCCC00000CCCCCCCCCCCCCCCCCCCCCCC000000
00CCCCCCCCCCCCCCCCCCCCCCCC0000CCCCCCCCCCCCCCCCCCCCCCCC0000
00CCCCCCCCCCCCCCCCCCCCCCCCC00FFFDCCCCCCCCCCCCCCCCCCCCCC000
00CCCCCCCCCCCCCCCCCCCCCCCCCCC0FFFECCCCCCCCCCCCCCCCCCCCCCC0
00CCCCCCCCCCCCCCCCCCCCCCCCCCCC0FFFFDCCCCCCCCCCCCCCCCCCCCCC
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCC0FFFFDCCCCCCCCCCCCCCCCCCCCD
00CCCCCCCCCCCCCCCCCCCCCCCCCCCDF000FDCCCCCCCCCCCCCCCCCCCCEF
00CCCCCCCCCCCCCCCCCCCCCCCCCCEFF00CCCCCCCCCCCCCCCCCCCCCDFFF
00CCCCCCCCCCCCCCCCCCCCCCCCDFFFF0CCCCCCCCCCCCCCCCCCCCCEFFFF
00CCCCCCCCCCCCCCCCCCCCCCCEFFFFCCCCCCCCCCCCCCCCCCCCCDFFFF00
00DDDDDDDDDDDDDCCCCCCCCDEFFF00CCCEEEEEEEEEECCCCCCCEFFFF000
00FFFFFFFFFFFFFECCCCCCEFFFF0000FFFFFFFFFFFECCCCCDFFFF00000
00FFFFFFFFFFFFFECCCCDEFFF00000FFFFFFFFFFFFECCCCEFFFF000000
00FFFFFFFFFFFFFDCCCEFFFF000000000000000000CCCDEFFF00000000
000000000000000CCDEFFFF0CCCCCCCCCCCCCCCCCCCCEFFFF000000000
0000000CCCCCCC0DEFFFF00CCCCCCCCCCCCCCCCCCCDEFFF00000000000
0000000ECCCCCC0FFFFF0CCCCCCCCCCCCCCCCCCCCCFFFF000000000000
0000000FCCCCCC0FFF00CCCCCCCCCCCCCCCCCCCCCCFF000C0000000000
0000000FDCCCCC0FF0CCCCCCCCCCCCCCCCCCCCCCCC000CCD0000000000
0000000FECCCCC000CCCCCCCCCCCCCCCCCCCCCCCCC00CCCE0000000000
00000000ECCCCC0CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCF0000000000
00000000FCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCF0000000000
00000000FDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDF0000000000
000000000FDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEF00000000000
000000000FFFEDDCCCCCCCCCCCCCCCCCCCCCCCCCCDEEFFF00000000000
000000000FFFFFFFEEEDDDDDCCCCCCCCDDDDDEEFFFFFFFF00000000000
00000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000
00000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000000
00000000000000000000FFFFFFFFFFFFFFF00000000000000000000000
}

sprite $Migration_AWSSnowball_importexport [58x58/16] {
00000000000000000CCCCCCCCCCCCCCCCCCCCCC0000000000000000000
000000000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00000000000
00000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0000000
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0000
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCD0
DCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDF0
FECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCEFF0
FFFEDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEFFFF0
EFFFFFEEDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDEFFFFFE00
CCFFFFFFFFFEEDDDDCCCCCCCCCCCCCCCCCCCCCCDDDDEEFFFFFFFFFDD00
DCCCFFFFFFFFFFFFFFFFFFEEEEEEEEEEEEEFFFFFFFFFFFFFFFFFCCCD00
ECCCCCCCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0CCCCCCE00
FCCCCCCCCCCCC00FFFFFFFFFFFFFFFFFFFFFFFFFF00CCCCCCCCCCCCF00
FDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCF00
0ECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDF00
0ECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCE000
0FCCCCCCCCCCCDECCCCCCCCCCCCCCCCCCCCCCCDFECCCCCCCCCCCCCF000
0FDCCCCCCCCCCDFFDCCCCCCCCCCCCCCCCCCCCCCFFEDCCCCCCCCCCDF000
00ECCCCCCCCCCDFFFECCCCCCCCCCCCCCCCCCCCCFFFFECCCCCCCCCEF000
00FCCCCCCCCCCC0FFFEDCCCCCCCCCCCCCCCCCCC00FFFEDCCCCCCCE0000
00FDCCCCCCCCCC00FFFFECCCCCCCCCCCCCCCCCC000FFFFECCCCCCF0000
00FDCCCCCCCCCC0000FFFEDCCCCCCCCCCCCCCCC0000FFFFECCCCDF0000
000EDDDDDDDDDD0CC00FFFFEDDDDDDDDDDDDDDD000CCCFFFFDCCEF0000
000FFFFFFFFFFF0CCCC0FFFFFFFFFFFFFFFFFFF000CCCCFFFFECE00000
000FFFFFFFFFFF0CCCCC00FFFFFFFFFFFFFFFFF000CCCCCCFFFFF00000
000FFFFFFFFFFF0CCCCCCC00000000000000000000CCCCCCCFFFF00000
000000000000000CCCCCCCC0000000000000000000CCCCCCCCCF000000
00CCCCCCCCCCCCCCCCCCCCCC00000CCCCCCCCCCCCCCCCCCCCCCC000000
00CCCCCCCCCCCCCCCCCCCCCCCC0000CCCCCCCCCCCCCCCCCCCCCCCC0000
00CCCCCCCCCCCCCCCCCCCCCCCCC00FFFDCCCCCCCCCCCCCCCCCCCCCC000
00CCCCCCCCCCCCCCCCCCCCCCCCCCC0FFFECCCCCCCCCCCCCCCCCCCCCCC0
00CCCCCCCCCCCCCCCCCCCCCCCCCCCC0FFFFDCCCCCCCCCCCCCCCCCCCCCC
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCC0FFFFDCCCCCCCCCCCCCCCCCCCCD
00CCCCCCCCCCCCCCCCCCCCCCCCCCCDF000FDCCCCCCCCCCCCCCCCCCCCEF
00CCCCCCCCCCCCCCCCCCCCCCCCCCEFF00CCCCCCCCCCCCCCCCCCCCCDFFF
00CCCCCCCCCCCCCCCCCCCCCCCCDFFFF0CCCCCCCCCCCCCCCCCCCCCEFFFF
00CCCCCCCCCCCCCCCCCCCCCCCEFFFFCCCCCCCCCCCCCCCCCCCCCDFFFF00
00DDDDDDDDDDDDDCCCCCCCCDEFFF00CCCEEEEEEEEEECCCCCCCEFFFF000
00FFFFFFFFFFFFFECCCCCCEFFFF0000FFFFFFFFFFFECCCCCDFFFF00000
00FFFFFFFFFFFFFECCCCDEFFF00000FFFFFFFFFFFFECCCCEFFFF000000
00FFFFFFFFFFFFFDCCCEFFFF000000000000000000CCCDEFFF00000000
000000000000000CCDEFFFF0CCCCCCCCCCCCCCCCCCCCEFFFF000000000
0000000CCCCCCC0DEFFFF00CCCCCCCCCCCCCCCCCCCDEFFF00000000000
0000000ECCCCCC0FFFFF0CCCCCCCCCCCCCCCCCCCCCFFFF000000000000
0000000FCCCCCC0FFF00CCCCCCCCCCCCCCCCCCCCCCFF000C0000000000
0000000FDCCCCC0FF0CCCCCCCCCCCCCCCCCCCCCCCC000CCD0000000000
0000000FECCCCC000CCCCCCCCCCCCCCCCCCCCCCCCC00CCCE0000000000
00000000ECCCCC0CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCF0000000000
00000000FCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCF0000000000
00000000FDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDF0000000000
000000000FDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEF00000000000
000000000FFFEDDCCCCCCCCCCCCCCCCCCCCCCCCCCDEEFFF00000000000
000000000FFFFFFFEEEDDDDDCCCCCCCCDDDDDEEFFFFFFFF00000000000
00000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000
00000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000000
00000000000000000000FFFFFFFFFFFFFFF00000000000000000000000
}


@enduml