---
output: svg
---
@startuml
skinparam rectangle {
    shadowing false
}
skinparam rectangle<<webApp>> {
    BackgroundColor #438DD5
    Shadowing<<webApp>> true
}
rectangle "no shadow"
rectangle "Web Application" <<webApp>> as web_app
@enduml
