---
output: svg
expected-description: (Gantt)
expected-status: 0
---
@startgantt
[Prototype design] lasts 13 days
[Test prototype] lasts 4 days
[Test prototype] ends 3 days before [Prototype design]'s end
@endgantt
