---
output: svg
expected-description: (Gantt)
expected-status: 0
---
@startgantt
[My task1] as [TASK1] lasts 4 days
[My task2] as [TASK2] lasts 6 days
[My task3] as [TASK3] lasts 8 days

TASK1 -> TASK3
TASK2 -> TASK3
@endgantt
