---
output: svg
---
@startuml
skinparam shadowing false
skinparam activityBorderColor white
skinparam activityBackgroundColor white
!definelong SALT(x)
"{{salt
!if x=='choose'
_choose()
!elseif x=='wait'
_wait()
!elseif x=='success'
_success()
!elseif x=='error'
_error()
!endif
}}
" as x
!enddefinelong

!definelong _choose()
{+
<b>an example
choose one option
()one
()two
[ok]
}
!enddefinelong

!definelong _wait()
{+
<b>please wait
operation in progress
<&clock>
[cancel]
}
!enddefinelong

!definelong _success()
{+
<b>success
congratulations!
[ok]
}
!enddefinelong
 
!definelong _error()
{+
<b>error
failed, sorry
[ok]
}
!enddefinelong


(*) --> SALT(choose)
-right-> SALT(wait)
wait -right-> SALT(success)
wait -down-> SALT(error)


@enduml
