@startuml
sprite $AmazonGlacier [68x83/16] {
00000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000FFCCC0000000000000000000000000000000
000000000000000000000000000000FFFFCCCCC00000000000000000000000000000
0000000000000000000000000000FFFFFFCCCCCCC000000000000000000000000000
00000000000000000000000000FFFFFFFFCCCCCCCCC0000000000000000000000000
000000000000000000000000FFFFFFFFFFCCCCCCCCCCC00000000000000000000000
0000000000000000000000FFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000FFDCCC000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000FFFDCC000
0FFFFDCCCCCCC00000000FFFFFFFFFFFFFCCCCCCCCCCCCC00000000FFFFFFFDCCCC0
FFFFFDCCCCCCCCCCC0000FFFFFFFFFFFFFCCCCCCCCCCCCC0000FFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCEFFFFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCDFFFFFFFFFFFFCCCCCCCCCCCCDFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCCCCCCFFFFFFFFFFFFFCCCCCCCCCCCCCFFFFFFFFFFFFFFFDCCCCC
FFFFFDCCCCCCCCCCC0000FFFFFFFFFFFFFCCCCCCCCCCCCC0000FFFFFFFFFFFDCCCCC
0FFFFDCCCCCCC00000000FFFFFFFFFFFFFCCCCCCCCCCCCC00000000FFFFFFFDCCCC0
0000FDCCC000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000FFFDC0000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
000000000000000000000FFFFFFFFFFFFFCCCCCCCCCCCCC000000000000000000000
00000000000000000000000FFFFFFFFFFFCCCCCCCCCCC00000000000000000000000
0000000000000000000000000FFFFFFFFFCCCCCCCCC0000000000000000000000000
000000000000000000000000000FFFFFFFCCCCCCC000000000000000000000000000
000000000000000000000000000000FFFFCCCCC00000000000000000000000000000
00000000000000000000000000000000FFCCC0000000000000000000000000000000
}



!define AMAZONGLACIER(alias) AWS_ENTITY(storage,#E05344,AmazonGlacier,alias,AmazonGlacier)

!define AMAZONGLACIER(alias,label) AWS_ENTITY(storage,#E05344,AmazonGlacier,label,alias,AmazonGlacier)

!definelong AMAZONGLACIER(alias,label,e_type="storage",e_color="#E05344",e_stereo="AmazonGlacier",e_sprite="AmazonGlacier")
AWS_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong

@enduml