@startuml
sprite $AWSCloudHSM [69x83/16] {
000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000FFCCC00000000000000000000000000000000
000000000000000000000000000000FFFFCCCCC000000000000000000000000000000
0000000000000000000000000000FFFFFFCCCCCCC0000000000000000000000000000
00000000000000000000000000FFFFFFFFCCCCCCCCC00000000000000000000000000
000000000000000000000000FFFFFFFFFFCCCCCCCCCCC000000000000000000000000
0000000000000000000000FFFFFFFFFFFFCCCCCCCCCCCCC0000000000000000000000
00000000000000000000FFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
0000000000000000000FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
0000000000000000000FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
0000000000000000000FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
0000000000000000000FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
0000000000000000000FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
0000000000000000000FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
000000FCC0000000000FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC0000000000FFDC000000
0000FFFCCCCCC000000FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC000000FFFFFFDCCC0000
00FFFFFCCCCCCCCCC00FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC000FFFFFFFFFDCCCCC00
FFFFFFFCCCCCCCCCC00FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC000FFFFFFFFFDCCCCCCC
FFFFFFFCCCCCCCCCC00FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC000FFFFFFFFFDCCCCCCC
FFFFFFFCCCCCCCCCC00FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC000FFFFFFFFFDCCCCCCC
FFFFFFFCCCCCCCCCC00FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC000FFFFFFFFFDCCCCCCC
FFFFFFFCCCCCCCCCC00FFFFFFFFFFFFFFFCCCCCCCCCCCCCCC000FFFFFFFFFDCCCCCCC
FFFFFFFCCCCCCCCCDFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCFFFFFFFFFDCCCCCCC
FFFFFFFCCCCCCDEFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCDEFFFFFFDCCCCCCC
FFFFFFFCCCDEFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCDEFFDCCCCCCC
FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCDCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCFFFFFFFFFFFFDCCCCCCC
00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00FFFFFFFFFFDCCCCC00
0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCC000000FFFFFFDCCC0000
000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCC0000000000FFDC000000
00000000FFFFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
0000000000FFFFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
000000000000FFFFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
00000000000000FFFFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
0000000000000000FFFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
000000000000000000FFFFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
00000000000000000000FFFFFFFFFFFFFFCCCCCCCCCCCCCCC00000000000000000000
0000000000000000000000FFFFFFFFFFFFCCCCCCCCCCCCC0000000000000000000000
000000000000000000000000FFFFFFFFFFCCCCCCCCCCC000000000000000000000000
00000000000000000000000000FFFFFFFFCCCCCCCCC00000000000000000000000000
0000000000000000000000000000FFFFFFCCCCCCC0000000000000000000000000000
000000000000000000000000000000FFFFCCCCC000000000000000000000000000000
00000000000000000000000000000000FFCCC00000000000000000000000000000000
}


@enduml