---
output: svg
---
@startuml

skinparam usecaseFontSize 8

"Main Admin" as Admin
"Use the application" as (Use)

User -> (Start)
User --> (Use) : A small label

Admin ---> (Use) : This is\nyet another\nlabel

@enduml
