---
output: svg
---
@startuml
skinparam titleFontSize 14
title
  Example of Tree
  |_ First line
  |_ **Bom(Model)**
  	|_ prop1
  	|_ prop2
  	|_ prop3
  |_ Last line
end title
[*] --> State1
@enduml
