---
output: svg
---
@startuml


!define my_red FF0000A0
!define my_blue 0000FFA0
!define my_green 00AA00A0



class "BigLibrary" as lib {
    + longnamedfunction
    + longnamedfunctionalsodifferent
}


class "SomeHandler" as handler
class "SomeHelper" as helper



handler -[#my_red]- lib::longnamedfunction
handler -[#my_red]- lib::longnamedfunctionalsodifferent




@enduml
