---
output: atxt, utxt, svg
expected-description: (3 participants)
---
@startuml
participant a

group p1
b -> c: msg
c --> b: OK
note right: Some right note
end

group p2
a -> b: msg
note left: Some left note
end
@enduml
