---
output: svg
---
@startuml
skinparam arrowColor<<read>> #green
skinparam arrowColor<<write>> #line.dashed:blue;text:coral
usecase usecase1
component component2
actor actor3
usecase1 --> component2 <<read>> : link1
usecase1 --> actor3 <<write>> : link2
@enduml
