/* ========================================================================
 * PlantUML : a free UML diagram generator
 * ========================================================================
 *
 * (C) Copyright 2009-2025, Arnaud Roques
 *
 * Project Info:  https://plantuml.com
 * 
 * If you like this project or if you find it useful, you can support us at:
 * 
 * https://plantuml.com/patreon (only 1$ per month!)
 * https://plantuml.com/paypal
 * 
 * This file is part of PlantUML.
 *
 * PlantUML is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PlantUML distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 *
 *
 * Original Author:  Arnaud Roques
 * 
 *
 */
package net.sourceforge.plantuml.teavm;

import java.util.Locale;

import net.sourceforge.plantuml.annotation.DuplicateCode;
import net.sourceforge.plantuml.klimt.UParam;
import net.sourceforge.plantuml.klimt.color.ColorMapper;
import net.sourceforge.plantuml.klimt.drawing.UDriver;
import net.sourceforge.plantuml.klimt.geom.USegment;
import net.sourceforge.plantuml.klimt.geom.USegmentType;
import net.sourceforge.plantuml.klimt.shape.DotPath;

/**
 * Driver for rendering DotPath (Bezier curves from Graphviz) in TeaVM/SVG.
 * 
 * DotPath is used for edges/links in diagrams generated by Graphviz.
 * It consists of a series of cubic Bezier curves.
 */
public class DriverDotPathTeaVM implements UDriver<DotPath, SvgGraphicsTeaVM> {

	@Override
	public void draw(DotPath shape, double x, double y, ColorMapper mapper, UParam param, SvgGraphicsTeaVM svg) {
		// ::uncomment when __TEAVM__
//		if (param.getColor().isTransparent())
//			return;
//
//		DriverRectangleTeaVM.applyStrokeColor(svg, mapper, param);
//		svg.setFillColor("none");
//		svg.setStrokeWidth(param.getStroke().getThickness());
//
//		// Convert DotPath to UPath and build SVG path data
//		final StringBuilder pathData = new StringBuilder();
//
//		for (USegment seg : shape.toUPath()) {
//			final USegmentType type = seg.getSegmentType();
//			final double[] coord = seg.getCoord();
//
//			if (type == USegmentType.SEG_MOVETO) {
//				pathData.append("M").append(format(coord[0] + x)).append(",").append(format(coord[1] + y)).append(" ");
//			} else if (type == USegmentType.SEG_CUBICTO) {
//				pathData.append("C")
//						.append(format(coord[0] + x)).append(",").append(format(coord[1] + y)).append(" ")
//						.append(format(coord[2] + x)).append(",").append(format(coord[3] + y)).append(" ")
//						.append(format(coord[4] + x)).append(",").append(format(coord[5] + y)).append(" ");
//			}
//		}
//
//		svg.drawPath(pathData.toString().trim());
		// ::done
	}

	@DuplicateCode(reference = "SvgGraphics#format")
	private String format(double x) {
		if (x == 0.0)
			return "0";

		String s = String.format(Locale.US, "%.4f", x);

		final int dot = s.indexOf('.');
		if (dot >= 0) {
			int end = s.length() - 1;
			while (end > dot && s.charAt(end) == '0')
				end--;

			if (end == dot)
				end--;

			s = s.substring(0, end + 1);
		}
		return s;
	}

}
