/* ========================================================================
 * PlantUML : a free UML diagram generator
 * ========================================================================
 *
 * (C) Copyright 2009-2026, Arnaud Roques
 *
 * Project Info:  https://plantuml.com
 *
 * If you like this project or if you find it useful, you can support us at:
 *
 * https://plantuml.com/patreon (only 1$ per month!)
 * https://plantuml.com/paypal
 *
 * This file is part of PlantUML.
 *
 * PlantUML is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PlantUML distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 *
 *
 * Original Author:  Arnaud Roques
 *
 */
package net.sourceforge.plantuml.teavm;

import net.sourceforge.plantuml.FileFormat;
import net.sourceforge.plantuml.klimt.font.StringBounder;
import net.sourceforge.plantuml.klimt.font.UFont;
import net.sourceforge.plantuml.klimt.geom.XDimension2D;

/**
 * Headless {@link StringBounder} that estimates text dimensions without any AWT
 * {@code FontMetrics} nor any browser {@code Canvas}/DOM access.
 * <p>
 * It relies on precomputed advance-width tables for the most frequent
 * characters (printable ASCII, Latin-1 Supplement, Greek, Cyrillic) and on
 * per-range Unicode rules for everything else (full-width CJK, zero-width
 * combining marks, a single narrow fallback). All widths are expressed for a
 * reference font size of {@value #REFERENCE_SIZE} and scaled linearly to the
 * requested size.
 * <p>
 * The advance tables are produced offline by {@link StringBounderMetricsGenerator}
 * (run on a standard JVM where AWT {@code FontMetrics} is available) and pasted
 * back here.
 * <p>
 * The estimation is deliberately approximate: when combined with the SVG
 * {@code textLength}/{@code lengthAdjust="spacing"} mechanism, any residual
 * error becomes a mild inter-character spacing adjustment rather than a layout
 * break.
 */
public class StringBounderMetrics implements StringBounder {
	// ::remove file when JAVA8

	/**
	 * Reference font size for which {@link #ADVANCE} is calibrated.
	 */
	private static final double REFERENCE_SIZE = 12.0;

	/**
	 * Advance width for ASCII 32 (space) to 126 (tilde), measured with a
	 * sans-serif font at size {@value #REFERENCE_SIZE}. Generated offline from real
	 * {@code FontMetrics} (see StringBounderDeterministic#main).
	 */
	private static final double[] ADVANCE = { 3.3, 3.3, 4.3, 6.7, 6.7, 10.7, 8.0, 2.3, 4.0, 4.0, 4.7, 7.0, 3.3, 4.0,
			3.3, 3.3, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 3.3, 3.3, 7.0, 7.0, 7.0, 6.7, 12.2, 8.0, 8.0,
			8.7, 8.7, 8.0, 7.3, 9.3, 8.7, 3.3, 6.0, 8.0, 6.7, 10.0, 8.7, 9.3, 8.0, 9.3, 8.7, 8.0, 7.3, 8.7, 8.0, 11.3,
			8.0, 8.0, 7.3, 3.3, 3.3, 3.3, 5.6, 6.7, 4.0, 6.7, 6.7, 6.0, 6.7, 6.7, 3.3, 6.7, 6.7, 2.7, 2.7, 6.0, 2.7,
			10.0, 6.7, 6.7, 6.7, 6.7, 4.0, 6.0, 3.3, 6.7, 6.0, 8.7, 6.0, 6.0, 6.0, 4.0, 3.1, 4.0, 7.0 };

	/**
	 * First code point of {@link #LATIN1_SUP}: Latin-1 Supplement block.
	 */
	private static final int LATIN1_SUP_BASE = 0x00A0;

	/**
	 * Advance width for the Latin-1 Supplement block (0x00A0-0x00FF). Generated by
	 * {@link StringBounderMetricsGenerator}. A value <= 0 means "not measured / not
	 * a normal proportional glyph" and falls through to the generic rules.
	 */
	private static final double[] LATIN1_SUP = {};

	/**
	 * First code point of {@link #GREEK}: Greek and Coptic block.
	 */
	private static final int GREEK_BASE = 0x0370;

	/**
	 * Advance width for the Greek and Coptic block (0x0370-0x03FF). Generated by
	 * {@link StringBounderMetricsGenerator}.
	 */
	private static final double[] GREEK = {};

	/**
	 * First code point of {@link #CYRILLIC}: Cyrillic block.
	 */
	private static final int CYRILLIC_BASE = 0x0400;

	/**
	 * Advance width for the Cyrillic block (0x0400-0x04FF). Generated by
	 * {@link StringBounderMetricsGenerator}.
	 */
	private static final double[] CYRILLIC = {};

	/**
	 * Fallback advance for a "normal" proportional glyph not present in the table
	 * (most Latin-1 supplement letters, Greek, Cyrillic, punctuation...).
	 */
	private static final double FALLBACK_NARROW = 6.7;

	/**
	 * Advance for a full-width glyph (CJK ideographs, Hiragana, Katakana, Hangul,
	 * full-width forms): roughly one em.
	 */
	private static final double FALLBACK_WIDE = 12.0;

	/**
	 * Bold faces are slightly wider than the regular table; this multiplier keeps
	 * the estimate plausible without a dedicated bold table.
	 */
	private static final double BOLD_FACTOR = 1.05;

	private final FileFormat fileFormat;

	public StringBounderMetrics(FileFormat fileFormat) {
		this.fileFormat = fileFormat;
	}

	@Override
	public FileFormat getFileFormat() {
		return fileFormat;
	}

	@Override
	public XDimension2D calculateDimension(UFont font, String text) {
		if (text == null || text.isEmpty())
			return new XDimension2D(0, 0);

		final double size = font.getSize2D();
		final double scale = size / REFERENCE_SIZE;
		final boolean bold = font.getFontFace().isBold();

		double width = 0;
		// Iterate by Unicode code point so that supplementary characters
		// (emoji, rare CJK in the SMP) are counted as a single glyph.
		int i = 0;
		final int length = text.length();
		while (i < length) {
			final int cp = text.codePointAt(i);
			width += advanceOf(cp);
			i += Character.charCount(cp);
		}

		if (bold)
			width *= BOLD_FACTOR;

		return new XDimension2D(width * scale, size);
	}

	/**
	 * Returns the advance width of a single code point at the reference size.
	 */
	private static double advanceOf(int cp) {
		// Fast path: printable ASCII covered by the calibrated table.
		if (cp >= 32 && cp <= 126)
			return ADVANCE[cp - 32];

		// Zero-width: combining marks, zero-width space/joiners, BOM, format chars.
		if (isZeroWidth(cp))
			return 0;

		// Measured proportional scripts: Latin-1 Supplement, Greek, Cyrillic.
		final double fromTable = fromRangeTable(cp);
		if (fromTable > 0)
			return fromTable;

		// Full-width scripts (CJK & friends): one em.
		if (isWide(cp))
			return FALLBACK_WIDE;

		// Everything else (rarer scripts, symbols...).
		return FALLBACK_NARROW;
	}

	/**
	 * Looks up a code point in the per-range measured tables. Returns the measured
	 * advance, or 0 when the code point is outside every table or was not measured
	 * (the caller then applies the generic rules).
	 */
	private static double fromRangeTable(int cp) {
		final int latin1 = cp - LATIN1_SUP_BASE;
		if (latin1 >= 0 && latin1 < LATIN1_SUP.length)
			return LATIN1_SUP[latin1];

		final int greek = cp - GREEK_BASE;
		if (greek >= 0 && greek < GREEK.length)
			return GREEK[greek];

		final int cyrillic = cp - CYRILLIC_BASE;
		if (cyrillic >= 0 && cyrillic < CYRILLIC.length)
			return CYRILLIC[cyrillic];

		return 0;
	}

	/**
	 * Code points that occupy no horizontal advance: combining diacritical marks
	 * and a few well-known zero-width / format characters.
	 */
	private static boolean isZeroWidth(int cp) {
		// Combining Diacritical Marks and the common extensions.
		if (cp >= 0x0300 && cp <= 0x036F) // Combining Diacritical Marks
			return true;
		if (cp >= 0x1AB0 && cp <= 0x1AFF) // Combining Diacritical Marks Extended
			return true;
		if (cp >= 0x1DC0 && cp <= 0x1DFF) // Combining Diacritical Marks Supplement
			return true;
		if (cp >= 0x20D0 && cp <= 0x20FF) // Combining Diacritical Marks for Symbols
			return true;
		if (cp >= 0xFE20 && cp <= 0xFE2F) // Combining Half Marks
			return true;

		// Discrete zero-width / format code points.
		if (cp == 0x200B) // ZERO WIDTH SPACE
			return true;
		if (cp == 0x200C) // ZERO WIDTH NON-JOINER
			return true;
		if (cp == 0x200D) // ZERO WIDTH JOINER
			return true;
		if (cp == 0xFEFF) // ZERO WIDTH NO-BREAK SPACE / BOM
			return true;

		return false;
	}

	/**
	 * Code points rendered as full-width (about one em) in typical fonts: the main
	 * CJK blocks, Japanese kana, Hangul, and full-width Latin forms.
	 */
	private static boolean isWide(int cp) {
		if (cp >= 0x1100 && cp <= 0x115F) // Hangul Jamo
			return true;
		if (cp >= 0x2E80 && cp <= 0x303E) // CJK Radicals, Kangxi, CJK Symbols
			return true;
		if (cp >= 0x3041 && cp <= 0x33FF) // Hiragana, Katakana, CJK symbols/letters
			return true;
		if (cp >= 0x3400 && cp <= 0x4DBF) // CJK Extension A
			return true;
		if (cp >= 0x4E00 && cp <= 0x9FFF) // CJK Unified Ideographs
			return true;
		if (cp >= 0xA000 && cp <= 0xA4CF) // Yi
			return true;
		if (cp >= 0xAC00 && cp <= 0xD7A3) // Hangul Syllables
			return true;
		if (cp >= 0xF900 && cp <= 0xFAFF) // CJK Compatibility Ideographs
			return true;
		if (cp >= 0xFE30 && cp <= 0xFE4F) // CJK Compatibility Forms
			return true;
		if (cp >= 0xFF00 && cp <= 0xFF60) // Fullwidth Forms
			return true;
		if (cp >= 0xFFE0 && cp <= 0xFFE6) // Fullwidth signs
			return true;
		if (cp >= 0x1F300 && cp <= 0x1FAFF) // Emoji & pictographs (SMP)
			return true;
		if (cp >= 0x20000 && cp <= 0x3FFFD) // CJK Extensions B-G (SMP)
			return true;

		return false;
	}

}
