---
output: svg
---
@startuml          
                   
package "output" {
  object foo      
    foo : bar      
}                  
                   
package "thing" {  
  map getfoobar {  
    makeit *--> output.foo
  }                
}                  
                   
@enduml     
