---
output: svg
---
@startuml
<style>
root {
  FontColor Red
}
</style>
title How to change fontcolor by style?
state A {
  state B {
  }
  state C {
    state c : state c
  }
}
 
state S1 : state S1
state S2

@enduml
