/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
	id("net.sourceforge.plantuml.java-application-conventions")
}

dependencies {
	implementation("org.apache.commons:commons-text")
	implementation(project(":legacy"))
	implementation(project(":utilities"))
}

application {
	// Define the main class for the application.
	mainClass.set("net.sourceforge.plantuml.app.App")
}
