@startuml
sprite $oracleDBinstance [54x58/16] {
0000000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0000000
00000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00000
000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC000
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00
0CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0
0CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0
CCCCCCCCAABCCCCCCCCCCCCCCCCCCCCAAACCCCCCCCCCCCCCCCCCCC
CCCCCC900006C7000009CCC6008CCB40005C705CCCA000005CCCCC
CCCCCC00460097005000BCC0005CC6007007705CCCA000005CCCCC
CCCCCA00BC406705CA00ACA0000CC009C605705CCCA00CCCCCCCCC
CCCCC800CC705705CB00AC80640AC00AC957705CCCA00CCCCCCCCC
CCCCC700CC7057047404CC607607A00ACCCC705CCCA000007CCCCC
CCCCC700CC7057000007CC00A804A00ACCCC705CCCA000007CCCCC
CCCCC700CC705704A700CA007600A00AC955705CCCA00CCCCCCCCC
CCCCC900CC605705CB00A7000000900AC704705CCCA00CCCCCCCCC
CCCCCB008B407705CC00A506AA407406C4067047777007777CCCCC
CCCCCC500000B705CC009008CC704800000A7000005000000CCCCC
CCCCCCC8556ACA79CC77877BCCA77C9656ACA777779777777CCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDDDDDDDDDDDDCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEEFFFFFFFFFFFFFFEEDCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCEFFFFFFFFFFFFFFFFFFFFFFE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCEFFFFFF000000000000FFFFFF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCEFF000000CCCCCCCCC00000FF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCD0000CCCCCCCCCCCCCCCCCC00
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00DCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00EDCCCCCCCCCCCCCCCCCDEF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00FFFEEDDDDDDDDDDDDEEFFF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00FFFFFFFFFFFFFFFFFFFFFF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC000FFFFFFFFFFFFFFFFFFF00
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CC0000FFFFFFFFFF000CCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCCCC00000000CCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCC0007CCC9000ACCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCC0004CCC7000ACCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCC0000CCC5000ACCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCC00009CC0000ACCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCC00407CA0500ACCCCC
DCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCC00705C70700ACCCCC
DCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCC00900C50A00ACCCCC
ECCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCC00A40A00C00ACCCCC
FCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCC00A70605C00ACCCCC
FDCCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCC00A90007C00ACCCCC
FECCCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCC00AC000AC00ACCCCC
0FECCCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCC00AC400CC00ACCCCC
0FFECCCCCCCCCCCCCCCCCCCCCCCCCC00CCCCC00AC604CC00ACCCCC
00FFEDCCCCCCCCCCCCCCCCCCCCCCCC00CCCCCAACCBAACCAACCCCCC
00FFFFEEDDDDDDDDDDDDDDDDDDDDDDD0EDCCCCCCCCCCCCCCCCCDEF
000FFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFEEDDDDDDDDDDDEEFFFF
00000FFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFF
000000000FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFF00
00000000000000000000000000000000000000FFFFFFFFF0000000
}



!define ORACLEDBINSTANCE(alias) AWS_ENTITY(component,#2F74B8,oracleDBinstance,alias,oracleDBinstance)

!define ORACLEDBINSTANCE(alias,label) AWS_ENTITY(component,#2F74B8,oracleDBinstance,label,alias,oracleDBinstance)

!definelong ORACLEDBINSTANCE(alias,label,e_type="component",e_color="#2F74B8",e_stereo="oracleDBinstance",e_sprite="oracleDBinstance")
AWS_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong

@enduml