---
output: debug, utxt
expected-description: (2 participants)
expected-image-count: 2
expected-debug-1:
  contains: hello1
  not-contains: hello2
expected-debug-2:
  contains: hello2
  not-contains: hello1
---
@startuml
Alice -> Bob : hello1
newpage
Alice -> Bob : hello2
@enduml
