@startuml
sprite $AmazonRekognition [68x82/16] {
0000000000000000000000000000000DDDAA00000000000000000000000000000000
00000000000000000000000000000DDDDDAAAA000000000000000000000000000000
000000000000000000000000000DDDDDDDAAAAAA0000000000000000000000000000
0000000000000000000000000DDDDDDDDDAAAAAAAA00000000000000000000000000
00000000000000000000000DDDDDDDDDDDAAAAAAAAAA000000000000000000000000
000000000000000000000DDDDDDDDDDDDDAAAAAAAAAAAA0000000000000000000000
0000000000000000000DDDDDDDDDDDDDDDAAAAAAAAAAAAAA00000000000000000000
00000000000000000DDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAA000000000000000000
000000000000000DDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAA0000000000000000
0000000000000DDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAA00000000000000
00000000000DDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAA000000000000
000000000DDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAA0000000000
0000000DDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAA00000000
00000DDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAA000000
000DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0000
0DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEDADDCCBAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDEEEEFFFFEDDAADFFFEDCCBAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDEEEEFFFFFFFFEDDDAAADFFFFFFFEDCCBAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDEEEEFFFFFFFFFFFFEDDDDAAAACFFFFFFFFFFFEDCCBAAAAAAAAAAAAA
DDDDDDDDEEEEFFFFFFFFFFFFFFFFEDDDDDAAAAABFFFFFFFFFFFFFFFEDCCBAAAAAAAA
DDDDDDDBBCCDDDFFFFFFFFF000DDDDDDDDAAAAAAAA000FFFFFFEEEEEEEEDDAAAAAAA
DDDDDDDAAAAAAAAAA00000000DDDDDDDDDAAAAAAAAA00000000DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA0000000DDDDDDDDDDAAAAAAAAAA0000000DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA000000DDDDDDDDDDDAAAAAAAAAAA000000DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA00000DDDDDDDDDDDDAAAAAAAAAAAA00000DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA0000DDDDDDDDDDDDDAAAAAAAAAAAAA0000DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA000DDDDDDDDDDDDDDAAAAAAAAAAAAAA000DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA00DDDDDDDDDDDDDDDAAAAAAAAAAAAAAA00DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA0DDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAA0DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAADDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAADDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAADDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAABDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAADDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAABDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAADDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAADDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA0DDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAA0DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA00DDDDDDDDDDDDDDDAAAAAAAAAAAAAAA00DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA000DDDDDDDDDDDDDDAAAAAAAAAAAAAA000DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA0000DDDDDDDDDDDDDAAAAAAAAAAAAA0000DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA00000DDDDDDDDDDDDAAAAAAAAAAAA00000DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA000000DDDDDDDDDDDAAAAAAAAAAA000000DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA0000000DDDDDDDDDDAAAAAAAAAA0000000DDDDDDDDDDAAAAAAA
DDDDDDDAAAAAAAAAA00000000DDDDDDDDDAAAAAAAAA00000000DDDDDDDDDDAAAAAAA
DDDDDDD9999888777777777000DDDDDDDDAAAAAAAA000777777899AACCCDDAAAAAAA
DDDDDDDDCBA97777777777777777CDDDDDAAAAA97777777777777777899AAAAAAAAA
DDDDDDDDDDDDDCBA9777777777777BDDDDAAAA9777777777777899AAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDCBA977777777ADDDAAA877777777899AAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDCBA97777ADDAA87777899AAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDCBA9ACA8899AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
0DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
000DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0000
00000DDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAA000000
0000000DDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAA00000000
000000000DDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAA0000000000
00000000000DDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAA000000000000
0000000000000DDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAA00000000000000
000000000000000DDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAA0000000000000000
00000000000000000DDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAA000000000000000000
0000000000000000000DDDDDDDDDDDDDDDAAAAAAAAAAAAAA00000000000000000000
000000000000000000000DDDDDDDDDDDDDAAAAAAAAAAAA0000000000000000000000
00000000000000000000000DDDDDDDDDDDAAAAAAAAAA000000000000000000000000
0000000000000000000000000DDDDDDDDDAAAAAAAA00000000000000000000000000
000000000000000000000000000DDDDDDDAAAAAA0000000000000000000000000000
00000000000000000000000000000DDDDDAAAA000000000000000000000000000000
0000000000000000000000000000000DDDAA00000000000000000000000000000000
}



!define AMAZONREKOGNITION(alias) AWS_ENTITY(component,#2F74B8,AmazonRekognition,alias,AmazonRekognition)

!define AMAZONREKOGNITION(alias,label) AWS_ENTITY(component,#2F74B8,AmazonRekognition,label,alias,AmazonRekognition)

!definelong AMAZONREKOGNITION(alias,label,e_type="component",e_color="#2F74B8",e_stereo="AmazonRekognition",e_sprite="AmazonRekognition")
AWS_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong

@enduml