@startuml
sprite $DBinstance [44x58/16] {
00000000000000CCCCCCCCCCCCCCCC00000000000000
0000000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0000000
0000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0000
0CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
ECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCE
FECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCEF
FFFEDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEFFF
DFFFFFEEDDCCCCCCCCCCCCCCCCCCCCCCCCDDEEFFFFFD
C0FFFFFFFFFEEEDDDDDDDDDDDDDDDDEEEFFFFFFFFF0C
CCC0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0CCC
CCCCC000FFFFFFFFFFFFFFFFFFFFFFFFFFFF000CCCCC
CCCCCCCCCC000000FFFFFFFFFFFF000000CCCCCCCCCC
CCCCCCCCCCCCCCCCCCC000000CCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCC0000000000CCCCCCCC0000000000CCCCCCCC
CCCCCCCC0000000000ACCCCCCA0000000000CCCCCCCC
CCCCCCCC00000000008CCCCCC80000000000CCCCCCCC
CCCCCCCC00000000006CCCCCC60000000000CCCCCCCC
CCCCCCCC00000000000CCCCCC00000000000CCCCCCCC
CCCCCCCC00000000000ACCCCA00000000000CCCCCCCC
CCCCCCCC000000000007CCCC700000000000CCCCCCCC
CCCCCCCC000000500005CCCC500005000000CCCCCCCC
CCCCCCCC000000700000CCCC000007000000CCCCCCCC
CCCCCCCC000000A00000ACCA00000A000000CCCCCCCC
CCCCCCCC000000A600007CC700006A000000CCCCCCCC
CCCCCCCC000000A900005CC500009A000000CCCCCCCC
CCCCCCCC000000AB00000CC00000BA000000CCCCCCCC
CCCCCCCC000000AC400009900004CA000000CCCCCCCC
CCCCCCCC000000AC700007700007CA000000CCCCCCCC
CCCCCCCC000000AC900004400009CA000000CCCCCCCC
CCCCCCCC000000ACC0000000000CCA000000CCCCCCCC
CCCCCCCC000000ACC5000000005CCA000000CCCCCCCC
CCCCCCCC000000ACC8000000008CCA000000CCCCCCCC
CCCCCCCC000000ACCA00000000ACCA000000CCCCCCCC
CCCCCCCC000000ACCC00000000CCCA000000CCCCCCCC
CCCCCCCC000000ACCC60000006CCCA000000CCCCCCCC
CCCCCCCC000000ACCC90000009CCCA000000CCCCCCCC
CCCCCCCC000000ACCCC000000CCCCA000000CCCCCCCC
CCCCCCCC000000ACCCC400004CCCCA000000CCCCCCCC
CCCCCCCCAAAAAACCCCCAAAAAACCCCCAAAAAACCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
DCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCD
FECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCEF
FFEEDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEEFF
FFFFFEEDDCCCCCCCCCCCCCCCCCCCCCCCCCCDDEEFFFFF
0FFFFFFFFFEEDDDDDDDDDDDDDDDDDDDDEEFFFFFFFFF0
0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000
0000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000
00000000000000FFFFFFFFFFFFFFFF00000000000000
}



!define DBINSTANCE(alias) AWS_ENTITY(component,#2F74B8,DBinstance,alias,DBinstance)

!define DBINSTANCE(alias,label) AWS_ENTITY(component,#2F74B8,DBinstance,label,alias,DBinstance)

!definelong DBINSTANCE(alias,label,e_type="component",e_color="#2F74B8",e_stereo="DBinstance",e_sprite="DBinstance")
AWS_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong

@enduml