@startuml
sprite $vault [48x67/16] {
0000000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0000000
000000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC000000
00000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00000
0000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0000
000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC000
00CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00
0CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0
0DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD0
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCC66BCCCCCCCB988889BCCCCCCCCCCCCCCCCCCCC
CCCCCCCCC9005ACCCCB7000000007BCCCCCCCCCCCCCCCCCC
CCCCCCCCCC80008CC90000000000009CCCCCCB77CCCCCCCC
CCCCCCCCCCCA5005B600000000000009CCCA6000BCCCCCCC
CCCCCCCCCCCCB6000B80007997000000BA600008BCCCCCCC
CCCCCCCCCCCCCC90008B8A7667B8008B600059CCCCCCCCCC
CCCCCCCCCCCCCCAA500560000008CA600059CCCCCCCCCCCC
CCCCCCCCCCCCCC50970000000000000059CCCCCCCCCCCCCC
CCCCCCCCCCCCCB00079000000000006A95BCCCCCCCCCCCCC
CCCCCCCCCCCCCA00058000000000089500ACCCCCCCCCCCCC
CCCCCCCCCCCCCA00067000000000086000ACCCCCCCCCCCCC
CCCCCCCCCCCCCA00068000000000086000BCCCCCCCCCCCCC
CCCCCCCCCCCCCB000090000000000A0000BCCCCCCCCCCCCC
CCCCCCCCCCCCCD00009500000000690000DCCCCCCCCCCCCC
CCCCCCCCCCCCCC80000A00000005B00008DCCCCCCCCCCCCC
CCCCCCCCCCCCCCD00005A600007A50000DCCCCCCCCCCCCCC
CCCCCCCCCCCCCCE800000A008A8000008ECCCCCCCCCCCCCC
CCCCCCCCCCCCCCCF60000A00A0000006FCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCDE7000800B000007EECCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCEFA00900A0000AFECCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCEFEBB00A57BEFECCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCDFF805DFFFFDCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCD806DEEDCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCC706CCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCC607CCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCC608CCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCC508CCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCAABCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}



!define VAULT(alias) AWS_ENTITY(storage,#E05344,vault,alias,vault)

!define VAULT(alias,label) AWS_ENTITY(storage,#E05344,vault,label,alias,vault)

!definelong VAULT(alias,label,e_type="storage",e_color="#E05344",e_stereo="vault",e_sprite="vault")
AWS_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong

@enduml