@startuml
sprite $genericdatabase [44x58/16] {
000000000000CCCCCCCCCCCCCCCCCCC0000000000000
0000000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0000000
0000CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0000
0CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
ECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCE
FFDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDFF
FFFFEDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEFFFF
0FFFFFFEEDCCCCCCCCCCCCCCCCCCCCCCCCDEEFFFFFF0
C00FFFFFFFFFFEEEDDDDDDDDDDDDEEEFFFFFFFFFF0CC
CCC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00CCCC
CCCCCC0000FFFFFFFFFFFFFFFFFFFFFFFF000CCCCCCC
CCCCCCCCCCC0000000000000000000000CCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
ECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCD
FEDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCEF
FFFEDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDFFF
0FFFFFFEDDCCCCCCCCCCCCCCCCCCCCCCCCCCDDEFFFFF
00FFFFFFFFFFEEDDDCCCCCCCCCCCCDDDEEFFFFFFFF00
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000
000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000
0000000000000000FFFFFFFFFFFFFF00000000000000
}


@enduml