''
'' Author: Brett Schwarz
'' 

!$THEME = "resume-light"

!if %not(%variable_exists("$BGCOLOR"))
!$BGCOLOR = "transparent"
!endif

skinparam backgroundColor $BGCOLOR
skinparam useBetaStyle false


skinparam  {
    skinparam defaultFontName   "Verdana"
    skinparam defaultFontSize   12
    defaultTextAlignment        center
    shadowing                   false
    RoundCorner                 10
    TitleFontSize               18
}
<style>
    wbsDiagram {
        LineColor #f0f0f0
        BorderThickness 3
        BackgroundColor #f9f9f9
        FontColor #6a9fb5
        :depth(0) {
            fontSize 16
            fontStyle bold
        }
        :depth(1) {
            fontSize 14
            padding 5
            fontStyle bold
        }
        :depth(2) {
            fontSize 12
            padding 3
        }
        :depth(3) {
            fontSize 10
            padding 2
        }

    }
</style>
