---
output: svg
---
@startuml
class Object << general >>
Object <|--- ArrayList
note top of Object : In java , every class\nextends this one.
note "This is a floating note" as N1
note "This note is connected\nto several objects." as N2
N2..Object
N2 .. ArrayList

@enduml
