@startuml 
sprite $js_badge [48x48/16] {
000000000000000000000000000000000000000000000000
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFB7778FFFFFFFB64469FFFFFFFF8
6FFFFFFFFFFFFFFFFFFFF70002FFFFFC20000001AFFFFFF8
6FFFFFFFFFFFFFFFFFFFF70002FFFFC0000000000AFFFFF8
6FFFFFFFFFFFFFFFFFFFF70002FFFF300000000000EFFFF8
6FFFFFFFFFFFFFFFFFFFF70002FFFC00005DD7002BFFFFF8
6FFFFFFFFFFFFFFFFFFFF70002FFF90000FFFF87FFFFFFF8
6FFFFFFFFFFFFFFFFFFFF70002FFF90000FFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFF70002FFFB00006FFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFF70002FFFF0000029FFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFF70002FFFF700000018FFFFFFFF8
6FFFFFFFFFFFFFFFFFFFF70002FFFFF4000000019FFFFFF8
6FFFFFFFFFFFFFFFFFFFF70002FFFFFF8000000006FFFFF8
6FFFFFFFFFFFFFFFFFFFF70002FFFFFFFE600000008FFFF8
6FFFFFFFFFFFFFFFFFFFF70002FFFFFFFFFF8100000EFFF8
6FFFFFFFFFFFFFFFFFFFF70002FFFFFFFFFFFF60000AFFF8
6FFFFFFFFFFFFFFFFFFFF60002FFFFFDFFFFFFF10007FFF8
6FFFFFFFFFFFFFF77FFFF50003FFFE608FFFFFF10007FFF8
6FFFFFFFFFFFFB2009FFD00005FFA10007FFFF800009FFF8
6FFFFFFFFFFFE000002300000AFFB00000033000000EFFF8
6FFFFFFFFFFFF800000000002FFFF80000000000008FFFF8
6FFFFFFFFFFFFF6000000001DFFFFFA00000000007FFFFF8
6FFFFFFFFFFFFFFB4000017FFFFFFFFE82000015DFFFFFF8
6FFFFFFFFFFFFFFFFFEDEFFFFFFFFFFFFFFDDEFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8
6EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE7
}


!define DEV_JS_BADGE(_alias) ENTITY(rectangle,black,js_badge,_alias,DEV JS_BADGE)
!define DEV_JS_BADGE(_alias,_label) ENTITY(rectangle,black,js_badge,_label,_alias,DEV JS_BADGE)
!define DEV_JS_BADGE(_alias,_label,_shape) ENTITY(_shape,black,js_badge,_label,_alias,DEV JS_BADGE)
!define DEV_JS_BADGE(_alias,_label,_shape,_color) ENTITY(_shape,_color,js_badge,_label,_alias,DEV JS_BADGE)
skinparam folderBackgroundColor<<DEV JS_BADGE>> White
@enduml
