---
output: svg
---
@startuml
sprite bs1 <svg viewBox="0 0 16 16">
  <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M9.283 4.002H7.971L6.072 5.385v1.271l1.834-1.318h.065V12h1.312z"/>
</svg>

card "<$bs1>" as bs1
card a
card b
bs1 --> a : sprite: <$bs1>
a --> b #red: sprite: <$bs1>

legend <$bs1>
@enduml
