@startuml
sprite $topic [44x60/16] {
000000000CCCCCCCCCCCCCCCCCCCCCCCCCC000000000
000000000CCCCCCCCCCCCCCCCCCCCCCCCCC000000000
000000000C0CCCCCCCCCCCCCCCCCCCCCC0C000000000
000000000CC0CCCCCCCCCCCCCCCCCCCC0CC000000000
000000FFFDCCCCCCCCCCCCCCCCCCCCCCCCCFFF000000
000FFFFFFDCCCC0CCCCCCCCCCCCCC0CCCCCFFFFFF000
0FFFFFFFFDCCCCC0CCCCCCCCCCCC0CCCCCCFFFFFFFF0
FFFFFFFFFDCCCCCCC0CCCCCCCC0CCCCCCCCFFFFFFFFF
FFFFFFFFFDCCCCCCCC0CCCCCC0CCCCCCCCCFFFFFFFFF
FFFFFFFFFDCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFF
FFFFFFFFFDCCCCCCCCCCC00CCCCCCCCCCCCFFFFFFFFF
FFFFFFFFFDCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFF
0FFFFFFFFDCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFF0
00FFFFFFFEDDDCCCCCCCCCCCCCCCCCCDDDEFFFFFF000
CC000FFFFFFFFFFEEEEEDDDDEEEEEFFFFFFFFFF000CC
CCCC00000FFFFFFFFFFFFFFFFFFFFFFFFFF00000CCCC
CCCCCCC00000000000FFFFFFFF00000000000CCCCCCC
CCCCCCCCCCCC00000000000000000000CCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
EDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCE
FFEDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEF
FFFFEDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEFFF
00FFFFFEEDDDCCCCCCCCCCCCCCCCCCCCCCDDEEFFFFF0
00000FFFFFFFFEEEDDDDDDDDDDDDDDEEEFFFFFFF0000
00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000
000000000000000FFFFFFFFFFFFFFFF0000000000000
}

sprite $AWSIoT_topic [44x60/16] {
000000000CCCCCCCCCCCCCCCCCCCCCCCCCC000000000
000000000CCCCCCCCCCCCCCCCCCCCCCCCCC000000000
000000000C0CCCCCCCCCCCCCCCCCCCCCC0C000000000
000000000CC0CCCCCCCCCCCCCCCCCCCC0CC000000000
000000FFFDCCCCCCCCCCCCCCCCCCCCCCCCCFFF000000
000FFFFFFDCCCC0CCCCCCCCCCCCCC0CCCCCFFFFFF000
0FFFFFFFFDCCCCC0CCCCCCCCCCCC0CCCCCCFFFFFFFF0
FFFFFFFFFDCCCCCCC0CCCCCCCC0CCCCCCCCFFFFFFFFF
FFFFFFFFFDCCCCCCCC0CCCCCC0CCCCCCCCCFFFFFFFFF
FFFFFFFFFDCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFF
FFFFFFFFFDCCCCCCCCCCC00CCCCCCCCCCCCFFFFFFFFF
FFFFFFFFFDCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFFF
0FFFFFFFFDCCCCCCCCCCCCCCCCCCCCCCCCCFFFFFFFF0
00FFFFFFFEDDDCCCCCCCCCCCCCCCCCCDDDEFFFFFF000
CC000FFFFFFFFFFEEEEEDDDDEEEEEFFFFFFFFFF000CC
CCCC00000FFFFFFFFFFFFFFFFFFFFFFFFFF00000CCCC
CCCCCCC00000000000FFFFFFFF00000000000CCCCCCC
CCCCCCCCCCCC00000000000000000000CCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
EDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCE
FFEDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEF
FFFFEDDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDEFFF
00FFFFFEEDDDCCCCCCCCCCCCCCCCCCCCCCDDEEFFFFF0
00000FFFFFFFFEEEDDDDDDDDDDDDDDEEEFFFFFFF0000
00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000
000000000000000FFFFFFFFFFFFFFFF0000000000000
}


@enduml