@startuml
sprite $AmazonEMR [68x82/16] {
0000000000000000000000000000000DDDAA00000000000000000000000000000000
00000000000000000000000000000DDDDDAAAA000000000000000000000000000000
000000000000000000000000000DDDDDDDAAAAAAA000000000000000000000000000
0000000000000000000000000DDDDDDDDDAAAAAAAAA0000000000000000000000000
00000000000000000000000DDDDDDDDDDDAAAAAAAAAAA00000000000000000000000
000000000000000000000DDDDDDDDDDDDDAAAAAAAAAAAAA000000000000000000000
0000000000000000000DDDDDDDDDDDDDDDAAAAAAAAAAAAAAA0000000000000000000
00000000000000000DDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAA00000000000000000
000000000000000DDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAA000000000000000
0000000000000DDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAA0000000000000
00000000000DDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAA00000000000
000000000DDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAA000000000
0000000DDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAA0000000
00000DDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00000
000DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA000
0DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEFFEECCBAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDDDDDDDEEEFFFFFFFFFFFFFFEDCBBAAAAAAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDDDDDDEEEEFFFFFFFFFFFFFFFFFFFFFFFFFEDCBAAAAAAAAAAAAAAAAAA
DDDDDDDDDDDDEEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDCBAAAAAAAAAAAA
DDDDDDEEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEDCBAAAAAA
EEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEECCB
000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000
00000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000
0000000000000000000000000000000FFFFFF0000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DDDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
0DDBAAADDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00
0000000DDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0000
0000000DDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAAAA000000
0000000DDDDBAAAADDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAAAA00000000
000000000DDBAA00DDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAAAA0000000000
0000000000000000DDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAAAA000000000000
0000000000000000DDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAAAA00000000000000
0000000000000000DDDDDBAAAAADDDDDDCAAAAAAAAAAAAAAAAAA0000000000000000
00000000000000000DDDDBAAAA0DDDDDDCAAAAAAAAAAAAAAAA000000000000000000
0000000000000000000DDBAA000DDDDDDCAAAAAAAAAAAAAA00000000000000000000
000000000000000000000000000DDDDDDCAAAAAAAAAAAA0000000000000000000000
000000000000000000000000000DDDDDDCAAAAAAAAAA000000000000000000000000
000000000000000000000000000DDDDDDCAAAAAAAA00000000000000000000000000
000000000000000000000000000DDDDDDCAAAAAA0000000000000000000000000000
00000000000000000000000000000DDDDCAAAA000000000000000000000000000000
0000000000000000000000000000000DDCAA00000000000000000000000000000000
}



!define AMAZONEMR(alias) AWS_ENTITY(component,#F58536,AmazonEMR,alias,AmazonEMR)

!define AMAZONEMR(alias,label) AWS_ENTITY(component,#F58536,AmazonEMR,label,alias,AmazonEMR)

!definelong AMAZONEMR(alias,label,e_type="component",e_color="#F58536",e_stereo="AmazonEMR",e_sprite="AmazonEMR")
AWS_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong

@enduml