---
output: svg
---
@startuml
skinparam componentShadowing false
skinparam rectangleShadowing false
skinparam actorShadowing false
skinparam databaseShadowing false
actor actor
component component
rectangle rectangle
database database

rectangle r2 {
  node node
}
@enduml
