---
output: svg
---
@startuml
skinparam package {
    backgroundColor Yellow
    backgroundColor<<st>> LightBlue
}
package AA <<st>> {
  [ZZ]
}
package BB {
  [XX]
}
package EE <<st>> {
}
package FF <<st>> {
}
@enduml
