@startuml
sprite $configrule [50x64/16] {
CCCCCCCCCCCCCCCCC000000000000000000000000000000000
CCCCCCCCCCCCCCCCCC00000000000000000000000000000000
CCCCCCCCCCCCCCCCCCCC000000000000000000000000000000
CCCCCCCCCCCCCCCCCCCCC00000000000000000000000000000
CCCCCCCCCCCCCCCCCCCCCC0000000000000000000000000000
CCCCCCCCCCCCCCCCCCCCCCC000000000000000000000000000
CCCCCCCCCCCCCCCCCCCCCCCC00000000000000000000000000
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBACCCCABCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB009CC900BCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB0000990000BCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB0000000000BCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB00000000BCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB000000BCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC90000009CCCCC
DDDDDDDDDDDDDDDDCCCCCCCCCCCCCCCCCCCC9000000009CCCC
FFFFFFFFFFFFFFFFECCCCCCCCCCCCCCCCCCA0000000000ACCC
EEEEEEEEEEEEEEEEFECCCCCCCCCCCCCCCCCB0000BB0006CCCC
CCCCCCCCCCCCCCCCCFECCCCCCCCCCCCCCCCCB00BCCB06CCCCC
CCCCCCCCCCCCCCCCCCFFCCCCCCCCCCCCCCCCCBBCCCCBCCCCCC
CCCCCCCCCCCCCCCCCCCEFCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCEFCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCEFDDDDDDDDDDDDDDDDDDDDDDDDDDD
CCCCCCCCCCCCCCCCCCCCCCEFFFFFFFFFFFFFFFFFFFFFFFFFFF
CCCCCCCCCCCCCCCCCCCCCCCDEEEEEEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC97CCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC9007CCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC900008CC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC8BCCC900000BCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC700BC900000BCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC70000800000BCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC9000000000BCCCCC
EEEEEEEEEEEEEEEECCCCCCCCCCCCCCCCCCC90000000BCCCCCC
FFFFFFFFFFFFFFFFFCCCCCCCCCCCCCCCCCCC900000BCCCCCCC
CCCCCCCCCCCCCCCCEFDCCCCCCCCCCCCCCCCCC9000BCCCCCCCC
CCCCCCCCCCCCCCCCCEFDCCCCCCCCCCCCCCCCCC90BCCCCCCCCC
CCCCCCCCCCCCCCCCCCDFDCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCDFDCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCDFDCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCDFEEEEEEEEEEEEEEEEEEEEEEEEEEE
CCCCCCCCCCCCCCCCCCCCCCDFFFFFFFFFFFFFFFFFFFFFFFFFFF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC70BCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC7000BCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCCCC700007CC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB07CCC700006CCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB0007C700006CCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC00000000006CCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB000000006CCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB0000006CCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB00006CCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB006CCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCB7CCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}


@enduml