---
output: svg
---
@startuml
set separator none
state Foo1 ##[dotted]blue {
}
state Foo2 ##[dotted]green {
state inner1 ##[dotted]yellow
}

state out ##[dotted]gold

state Foo3 ##[bold]green {
state inner2 ##[dotted]yellow
}

out --> inner2
@enduml
